### PR TITLE
Fix kirby-slides breaking when slides input is updated 

### LINKED ISSUE #3112: [BUG] kirby slides sometimes breaks when `slides` input is updated
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When kirby-slides `slides` input is updated asynchronosly, but with a new object that causes us to re-render the individual slides without re-rendering the slides component itself, swiper.js no longer has the correct slides references to apply its styles to.

Expected: 
image

Actual: 
image

## Describe how to reproduce the bug
Repro (and suggested fix) by @troelslenda: https://github.com/kirbydesign/designsystem/compare/develop...reproduced-slides-bug

## Which Kirby version was used?
8.7.0

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3112

## What is the new behavior?
When kirby-slides slides input is updated asynchronosly, but with a new object that causes us to re-render the individual slides without re-rendering the slides template itself, swiper.js no longer has the correct slide element references to apply its styles/calculations to, causing the slides to lose all config like slides per view, gap etc. 
image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/slide/src/slides.component.ts [hunk 1]
```diff
@@ -93,6 +96,13 @@ export class SlidesComponent implements OnInit, AfterViewInit {
     this.swiperContainer.nativeElement.swiper.slideTo(index);
   }
 
+  ngOnChanges(changes: SimpleChanges): void {
+    if (changes?.slides.firstChange === false) {
```
Comment (jakobe) [inline libs/designsystem/slide/src/slides.component.ts]: Move conditional prop accessor:
```suggestion
    if (changes.slides?.firstChange === false) {
```

**Review by jakobe — CHANGES_REQUESTED** [review]

**Review by jakobe — APPROVED** [review]
