### PR TITLE
Close modal when clicking the browser back button

### LINKED ISSUE #2986: [BUG] Navigating with browser back/forward while modal is open will navigate openerpage
- [ x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When opening a modal and using back/forward functionality on web will navigate the opener-window and keep the modal on top

## Describe how to reproduce the bug

1. Go to "Til dig"
2. Click on Betal og overfør
3. Click "Back" in browser
4. Opener (the page from where the modal was opened)  will navigate and leave the modal where it is. Now the modal is orphanned and has lost its logic connection to the opener.  fx. onClose functions will not work.

## Which Kirby version was used?
It has allways been like this

## What was the expected behavior?
Either the back button should not work at all - or it should reproduce the browsers former state - like closing the modal before navigating the opener

## Please complete the following information:
- All OS
- All Browsers
- Probably all versions after IE-2.0 :-)

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by mark-drastrup**
## Which issue does this PR close?

This PR closes #2986

## What is the new behavior?
A normal modal (programatically instantiated, and not a router based modal) will now close, when clicking the browser back button.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any additional context?
This functionality does not apply to a programatically instantiated modal with an `alertConfig`

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.ts [hunk 1]
```diff
@@ -11,7 +11,8 @@ const config = {
 <button kirby-button kirbyModalRouterLink="page1" [kirbyModalQueryParams]="{awesomeQueryParam: 'awesome value'}" [kirbyAlertConfig]="alertConfig">Open modal by router link with alert</button>
 <button kirby-button class="deeplink" (click)="navigateToModalRoute(['/examples', 'modal', 'page1'], {awesomeQueryParam: 'awesome value'})">Deep link to modal route</button>
 <button kirby-button class="deeplink" [kirbyModalRouterLink]="['/examples', 'modal', 'page1']" [kirbyModalQueryParams]="{awesomeQueryParam: 'awesome value'}">Deep link to modal by router link</button>
-<button kirby-button class="deeplink" [kirbyModalRouterLink]="['/examples', 'modal-route-with-url-param', '1978', 'page1']">Deep link to modal with url param</button>`,
+<button kirby-button class="deeplink" [kirbyModalRouterLink]="['/examples', 'modal-route-with-url-param', '1978', 'page1']">Deep link to modal with url param</button>
+<button kirby-button class="deeplink" [kirbyModalRouterLink]="['/examples', 'modal-route-with-url-param', '1978', 'page1']" [kirbyAlertConfig]="alertConfig">Deep link to modal with alert</button>`,
```
Comment (jakobe) [inline apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.ts]: Should this new button be part of this PR or not? 🤔

File: libs/designsystem/modal/src/modal-navigation.service.ts [hunk 2]
```diff
@@ -340,4 +340,15 @@ export class ModalNavigationService {
     }
     return parentRoute;
   }
+
+  handleBackButton(modal: HTMLIonModalElement) {
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-navigation.service.ts]: Consider naming:
```suggestion
  handleBrowserBackButton(modal: HTMLIonModalElement) {
```

File: libs/designsystem/modal/src/modal-navigation.service.ts [hunk 3]
```diff
@@ -340,4 +340,15 @@ export class ModalNavigationService {
...
+    const popStateEvent$ = fromEvent(window, 'popstate');
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-navigation.service.ts]: Please inject `private windowRef: WindowRef` from `@kirbydesign/designsystem/types` in constructor and use this instead of global window object:
```suggestion
    const popStateEvent$ = fromEvent(this.windowRef, 'popstate');
```

Comment (jakobe) [inline libs/designsystem/modal/src/modal-navigation.service.ts]: Consider only handling 1 `popstate` event:
```suggestion
    const popStateEvent$ = fromEvent(window, 'popstate').pipe(first());
```

File: libs/designsystem/modal/src/modal-navigation.service.ts [hunk 4]
```diff
@@ -340,4 +340,15 @@ export class ModalNavigationService {
...
+    const popStateSubscription = popStateEvent$.subscribe(() => {
+      modal.dismiss();
+    });
+
+    modal.onDidDismiss().then(() => {
+      popStateSubscription.unsubscribe();
+    });
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-navigation.service.ts]: Consider simplifying 😊 

`takeUntil` ensures the observables completes when the modal closes and therefore we don't need to unsubscribe from the stream 🎉

See this detailed explanation: https://benlesh.medium.com/rxjs-dont-unsubscribe-6753ed4fda87 
And docs for `takeUntil`: https://rxjs.dev/api/index/function/takeUntil
```suggestion
    // convert Promise to Observable:
    const modalClose$ = from(modal, modal.onDidDismiss());
    // OR convert Event to Observable:
    // const modalClose$ = fromEvent(modal, 'ionModalDidDismiss');
    popStateEvent$.takeUntil(modalClose$).subscribe(() => {
      modal.dismiss();
    });
```

**Review by jakobe — COMMENTED** [review]
@mark-drastrup In general this looks really great!
I've added a few comments to simplify the observable stuff and only listen for 1 popstate event. Let me know if we should cover it a bit more in details over a call!

I totally follow your incentive to have the navigation service handle this (it is about navigation after all 😋 ), but a few things to consider:
1. Feature envy: The service is very keen on methods from the modal, so maybe this handling should happen in the modal itself (can't do as it's Ionic's) or in the service that creates the modal (`ModalHelperService`)
2. Adding to public API: should this method be exposed in `ModalNavigationService` or better to tug away in a private method on `ModalHelperService`? 🤔 
3. Crossing the wires: `ModalHelperService` currently doesn't have any references to `ModalNavigationService` - maybe leave it that way?

None of these are winning arguments in themselves, but I think all in all it could argue for making the back button handling a private method in `ModalHelperService` 🤷🏻 
What do you think? 😊

File: apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.ts (hunk 1 above)
Comment (mark-drastrup) [reply apps/cookbook/src/app/examples/modal-example/modal-example-outlet.component.ts]: Nice catch! It should no be part of this PR 😅

**Review by jakobe — APPROVED** [review]
Great job @mark-drastrup ! 👌🏻 🎉
