### PR TITLE
Form field: announce error text when nested interactive is focussed

### LINKED ISSUE #3680: [BUG] Form Field: The error messages below a form-field is never read from a screen reader
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When filling out a form field, an error message appears if it is incorrectly filled out. However when this error message appears it is never read aloud by the screen reader and thus the blind user will never be notified that the form field was incorrectly filled out

More info: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage

## Describe how to reproduce the bug

1. Find a form using kirby form fields
2. Turn on screen reader
3. Tab into kirby input
4. Type invalid input
5. Tab away and watch error message appear without the screen reader saying anything

## Add any screenshots
image

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3680

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 1]
```diff
@@ -149,18 +162,12 @@ export class FormFieldComponent
...
   ngAfterContentChecked(): void {
-    if (!this.inputElement) {
-      this.inputElement = this.element.querySelector('input, textarea');
+    if (!this.nestedInteractiveElement) {
+      this.initializeNestedInteractive();
+      this.subscribeToNestedInteractiveError();
     }
 
-    // TODO: remove "!this.inputElement.readOnly" when ionic has fixed input click issue
-    // https://github.com/ionic-team/ionic-framework/issues/22740
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/form-field/src/form-field.component.ts:158]: Checking for the readOnly property complicates the logic a bit as the `nestedInteractiveElement` can now also be a radio-group that does not have that property.

The linked issue is fixed by Ionic, so instead I tried to be a good scout and removed the logic.

I tested on a device, and inputs with readOnly cannot be focussed, while inputs without can be focussed with a single click as expected.

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 2]
```diff
@@ -39,22 +41,37 @@ export class FormFieldComponent
...
   showDefaultCalendarIcon = false;
 
+  _nestedInteractiveHasError: boolean;
   _labelId = UniqueIdGenerator.scopedTo('kirby-form-field-label').next();
+  _errorMessageId = UniqueIdGenerator.scopedTo('kirby-form-field-message').next();
+  _messageId = UniqueIdGenerator.scopedTo('kirby-form-field-message').next();
 
   @Input() label: string;
-  @Input() message: string | null;
+  @Input() get message(): string | null {
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts:61]: No need for getter/setter on Input if there are no side effects in any of the functions

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 3]
```diff
@@ -190,5 +193,57 @@ export class FormFieldComponent
...
+  }
+
+  private initializeNestedInteractiveElement() {
+    this.nestedInteractiveElement =
+      this.input?.nativeElement ||
+      this.textarea?.nativeElement ||
+      this.radioGroupElement?.nativeElement.querySelector('ion-radio-group');
+  }
+
+  private setNestedInteractiveElementAttributes() {
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts:209]: Call this from setter on message

Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts:209]: Read-up on the angular life-cycle to determine when the initialization and setting of element attributes should happen. (Does it make sense to have both "afterContentChecked" and "afterContentInit")

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 4]
```diff
@@ -190,5 +193,57 @@ export class FormFieldComponent
...
+    if (this.label && this.radioGroupElement) {
+      this.renderer.setAttribute(this.nestedInteractiveElement, 'aria-labelledby', this._labelId);
+    }
+  }
+
+  private subscribeToNestedInteractiveError() {
+    const nestedInteractiveComponent =
+      this.inputComponent || this.textareaComponent || this.radioGroupComponent;
+
+    this._nestedInteractiveHasError = nestedInteractiveComponent?.hasError;
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts]: Convert to boolean in the case that hasError does not exist on nestedInteractiveComponent (in the case that a new component has been added to the list of components that can be used in a formfield)
```suggestion
    this._nestedInteractiveHasError = !!nestedInteractiveComponent?.hasError;
```

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 5]
```diff
@@ -190,5 +193,57 @@ export class FormFieldComponent
...
+
+    this.nestedInteractiveErrorSubscription = nestedInteractiveComponent?.hasErrorChange.subscribe(
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts:237]: Add question mark if hasErrorChange is not defined in nestedInteractiveComponent
```suggestion
    this.nestedInteractiveErrorSubscription = nestedInteractiveComponent?.hasErrorChange?.subscribe(
```

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 6]
```diff
@@ -190,5 +193,57 @@ export class FormFieldComponent
...
+      );
+    }
+
+    if (this.label && this.radioGroupElement) {
+      this.renderer.setAttribute(this.nestedInteractiveElement, 'aria-labelledby', this._labelId);
+    }
+  }
+
+  private subscribeToNestedInteractiveError() {
+    const nestedInteractiveComponent =
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/form-field.component.ts:232]: Should we consider having an interface for all supported nestedInteractiveComponents to make sure they all implement "hasError" and "hasErrorChange"?

**Review by Fuzzy3 — CHANGES_REQUESTED** [review]

File: libs/designsystem/form-field/src/form-field.component.ts (hunk 5 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/form-field/src/form-field.component.ts:237]: The nestedInteractiveComponent is strongly typed due to this line above:
```
const nestedInteractiveComponent =
      this.inputComponent || this.textareaComponent || this.radioGroupComponent;
```

File: libs/designsystem/form-field/src/form-field.component.ts (hunk 6 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/form-field/src/form-field.component.ts:232]: Good idea!

File: libs/designsystem/form-field/src/form-field.component.ts (hunk 3 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/form-field/src/form-field.component.ts:209]: Good call, I've refactored it a bit to avoid duplicating stuff into the`AfterContentInit` hook.

File: libs/designsystem/types/src/form-field-control.ts [hunk 7]
```diff
@@ -0,0 +1,6 @@
+import { EventEmitter } from '@angular/core';
+
+export interface FormFieldControl {
```
Comment (Fuzzy3) [inline libs/designsystem/types/src/form-field-control.ts:3]: I ❤️ this

Comment (Fuzzy3) [reply libs/designsystem/types/src/form-field-control.ts:3]: Now that I'm looking at the hasError logic, I noticed its all the same lines of code. Maybe we should have a base FormFieldControl that all the other components extend?

**Review by Fuzzy3 — DISMISSED** [review]
Really nice job ! Just a single suggestion to make a base class for the formfieldcontrol. However i'm approving since that might be out of scope

File: libs/designsystem/types/src/form-field-control.ts (hunk 7 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/types/src/form-field-control.ts:3]: Good idea, would prefer if we add it in another PR for just that 🚀

**Review by Fuzzy3 — APPROVED** [review]
