### PR TITLE
Modal, Alert: label modal with title contents

### LINKED ISSUE #3677: [Enhancement] A11y improvements for Modal
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the enhancement
The following tasks should be completed to improve the a11y of the Modal component:

- [x] **Ensure modal is labelled with a title**
     - This can be achieved by associating `ion-title` of `modal-wrapper.component.html` to `ion-modal` through `aria-labelledby`. This could be set on the `ionModalElement` instance in `ModalWrapperComponent.ngOnInit`. 
     **Please note:** `ion-title` will need a unique id.
     More info: https://ionicframework.com/docs/api/modal#labels
- **Ensure the close button is labelled with a title**
  - This can be achieved by setting `aria-label` on the button in `modal-wrapper.component.html` since it's an icon only button with no text.
  **Please note:** The title should be localized (da + en).
  - [x] Moved to #3694 

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Refinement

- [ ] Request that the issue is [UX refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-refinement)
- [ ] Request that the issue is [tech refined](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#tech-refinement); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Publish a WIP implementation to Github as a draft PR and ask for feedback. 
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Update the [cookbook](https://cookbook.kirby.design) with examples and showcases.

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request. If you created a draft PR during implementation you can just mark that as "ready for review".

### LINKED ISSUE #3679: [BUG] Alert: missing announcement on open when screen reader is being used
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
There is no indication from the screen reader that an alert has been opened. An opening of an alert should be clearly announced in a such a way that the user knows that he/she should take some action.    

## Describe how to reproduce the bug

1. Open the cookbook and go to alert
2. Turn on a screen reader
3. Navigate to the "Show Alert" button and click it
4. Notice how the alert was opened but without an indication from the screen reader that it was opened.

## Add any screenshots

image

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3677 closes #3679 

## What is the new behavior?
**Background**
For all our different types of modals, we need a way to label them for assistive tech. We want to remove this burden from developers, so they do not have to re-visit every modal and apply a label.

One solution would be to use aria-labelledby as [recommended for modals with visible title bars](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role#labeling), but since IDs are scoped to the shadow root, this is not an option with ion-modal. The dialog element is within the modals shadow-root, while the title provided by us is in the light-dom, so any ID ref for the title is undefined in the dialogs tree. This is a general limitation ("feature") when working with shadow roots, and I have created a small example of this here: https://codepen.io/rasmooose/pen/dyxwWLa

Therefore we need to instead use the aria-label attribute and ensure that it is updated whenever the title changes. The most common use-case for a changing title is routed modal flows, where the same modal instance is reused for multiple views, but this could also simply be some async content.

---

We now sync the title to the `ion-modal` dialog elements aria-label. It is done via the modal wrapper and message state (empty state) component when used inside modals. 

This ensures that a title is set across the different types of modals and also the alert. 
A mutation observer or title setters are used where relevant to react to title changes and update the label of ancestor modals.

The only identified edge-case not supported by this pattern is compact modals without an empty state - in this case developers need to set the aria-label attribute themselves.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts [hunk 1]
```diff
@@ -27,14 +28,25 @@ import { CanDismissHelper } from '../../modal/services/can-dismiss.helper';
   host: { '[class.ion-page]': 'false' }, //Ensure ion-page class doesn't get applied by Ionic Modal Controller
 })
 export class ModalCompactWrapperComponent implements Modal, OnInit {
+  private _ariaLabel: string;
+
   @Input() config: ModalConfig;
   @Input() content: TemplateRef<any>;
+  @Input() set ariaLabel(value: string) {
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts]: All the added functionality here is because of the edge cases where a compact modal have no explicitly set title. As mentioned in the PR description, there is an alternative to this:

> The only identified edge-case not supported by this pattern is compact modals without an empty state - in this case developers need to inject the modal and set the ariaLabel property on the ModalCompactWrapperComponent.
> 
> If we do not want to introduce this additional functionality, we could document getModalDialogAncestor() as part of our public api and show consumers how to use it themselves and set the aria-label from their own component code instead.

Comment (RasmusKjeldgaard) [reply libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts]: I think I prefer to remove the functionality added here, and just expose `getModalDialogAncestor()`, to not clutter the `Modal` interface. But I left it in to support the discussion.

File: apps/cookbook/src/app/examples/modal-example/compact-example/modal-compact-example.component.ts [hunk 2]
```diff
@@ -2,10 +2,17 @@ import { Component, Optional, SkipSelf } from '@angular/core';
 
 import { Modal } from '@kirbydesign/designsystem';
 
+const config = {
+  ariaLabelPropertyCodeSnippet: `constructor(@Optional() @SkipSelf() private modal: Modal) {
+  this.modal.ariaLabel = 'My Custom Accessible Title';
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/modal-example/compact-example/modal-compact-example.component.ts]: See https://github.com/kirbydesign/designsystem/pull/3702/files#r1848593801.

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 3]
```diff
@@ -396,6 +398,19 @@ export class ModalWrapperComponent
     });
   }
 
+  private observeTitleContentChanges() {
+    observeContent(this.ionTitleElement.nativeElement, this.setTitleAsAriaLabel, this.willClose$);
+  }
+
+  private setTitleAsAriaLabel = () => {
+    if (!this.ionTitleElement) return;
+    const titleTextContent = this.ionTitleElement.nativeElement.textContent;
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Consider readability by adding a linebreak after the guard:
```suggestion
    if (!this.ionTitleElement) return;
    
    const titleTextContent = this.ionTitleElement.nativeElement.textContent;
```

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 4]
```diff
@@ -396,6 +398,19 @@ export class ModalWrapperComponent
...
+    const modalDialog = getModalDialogAncestor(this.elementRef.nativeElement);
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Should this be initialized once in `ngOnInit` or `ngAfterViewInit` as in empty state component? 🤔

File: libs/designsystem/helpers/src/content-mutation-observer.ts [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+    return true;
+  }
+  // Observe everything else.
+  return false;
+}
+
+export function observeContent(
+  observedElement: HTMLElement,
+  contentChangedCallback: () => void,
+  unobserve$?: Observable<void>
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.ts]: Consider replacing this param with a return function that the caller can use to unobserve the element

File: libs/designsystem/helpers/src/content-mutation-observer.ts [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+    characterData: true,
+    childList: true,
+    subtree: true,
+  });
+
+  unobserve$?.subscribe(() => {
+    mutationObserver.disconnect();
+  });
+
+  return mutationObserver;
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.ts]: Consider replacing the return value with a function that the caller can use to unobserve the element:
```suggestion
  return () => mutationObserver.disconnect();
```

File: libs/designsystem/modal/src/modal/services/alert.helper.spec.ts [hunk 7]
```diff
@@ -86,5 +87,14 @@ describe('AlertHelper', () => {
...
       await ionModalElement.dismiss();
     });
+
+    it('should set alert title text content as modal label', async () => {
+      await TestHelper.whenReady(ionModal);
+      const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
+
+      await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
+
+      expect(dialogElement.getAttribute('aria-label')).toBe(title);
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal/services/alert.helper.spec.ts:96]: Consider using built in matcher:
```suggestion
      expect(dialogElement).toHaveAttribute('aria-label', title);
```

File: libs/designsystem/modal/src/modal/services/alert.helper.spec.ts [hunk 8]
```diff
@@ -86,5 +87,14 @@ describe('AlertHelper', () => {
       expect(backdrop).toHaveComputedStyle({ '--backdrop-opacity': backdropOpacity });
       await ionModalElement.dismiss();
     });
+
+    it('should set alert title text content as modal label', async () => {
+      await TestHelper.whenReady(ionModal);
+      const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
+
+      await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal/services/alert.helper.spec.ts]: Consider readability, waiting for the attribute is also part of "Arrange":
```suggestion
      const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
      await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
```

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts [hunk 9]
```diff
@@ -370,3 +378,66 @@ describe('ModalWrapperComponent + PageProgressComponent', () => {
...
+  afterEach(() => {
+    spectator.setInput('isOpen', false);
+  });
+
+  it('should set modal title text content as modal label', async () => {
+    await TestHelper.whenReady(ionModal);
+    const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
+    await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
+
+    expect(dialogElement.getAttribute('aria-label')).toBe(modalTitle);
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts]: Consider using built in matcher:
```suggestion
    expect(dialogElement).toHaveAttribute('aria-label', modalTitle);
```

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts [hunk 10]
```diff
@@ -370,3 +378,66 @@ describe('ModalWrapperComponent + PageProgressComponent', () => {
...
+    expect(dialogElement).toHaveAttribute('aria-label', modalTitle);
+
+    const newTitle = 'Updated Modal Title';
+    const pageTitleComponent = spectator.query(PageTitleComponent);
+    pageTitleComponent['elementRef'].nativeElement.textContent = newTitle;
+
+    // Wait for aria-label to be updated
+    await TestHelper.whenTrue(() => dialogElement.getAttribute('aria-label') !== modalTitle);
+
+    expect(dialogElement.getAttribute('aria-label')).toBe(newTitle);
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts]: Consider using built in matcher:
```suggestion
    expect(dialogElement).toHaveAttribute('aria-label', newTitle);
```

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts [hunk 11]
```diff
@@ -370,3 +378,66 @@ describe('ModalWrapperComponent + PageProgressComponent', () => {
...
+
+    expect(dialogElement.getAttribute('aria-label')).toBe(modalTitle);
+  });
+
+  it('should update modal label when kirby-page-title content changes', async () => {
+    await TestHelper.whenReady(ionModal);
+    const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
+    await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
+
+    expect(dialogElement).toHaveAttribute('aria-label', modalTitle);
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.integration.spec.ts]: Consider readability, expecting on the initial modal title is also part of "Arrange":
```suggestion
    await TestHelper.whenReady(ionModal);
    const dialogElement = ionModal.shadowRoot.querySelector('[role="dialog"]');
    await TestHelper.whenTrue(() => dialogElement.hasAttribute('aria-label'));
    expect(dialogElement).toHaveAttribute('aria-label', modalTitle);
```

File: libs/designsystem/helpers/src/content-mutation-observer.spec.ts [hunk 12]
```diff
@@ -0,0 +1,86 @@
...
+  it('should create', () => {
+    expect(spectator.component).toBeTruthy();
+  });
+
+  it('should call callback when content changes', async () => {
+    const onContentChangeSpy = spyOn(spectator.component, 'onContentChange');
+
+    spectator.setInput('content', 'Updated content');
+    await TestHelper.waitForMutationObserver();
+    expect(onContentChangeSpy).toHaveBeenCalledTimes(1);
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.spec.ts]: Consider readability, Arrange -> Act -> Assert
```suggestion
    spectator.setInput('content', 'Updated content');
    await TestHelper.waitForMutationObserver();
    
    expect(onContentChangeSpy).toHaveBeenCalledTimes(1);
```

**Review by jakobe — COMMENTED** [review]
Good work 👏🏻

File: libs/designsystem/modal/src/modal/services/alert.helper.spec.ts (hunk 7 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/modal/src/modal/services/alert.helper.spec.ts:96]: `toHaveAttribute` does not exist here in the context of a spectator service factory, but will change it in the other places! 🙏

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts (hunk 4 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Good idea, optimized it a bit 👍

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 13]
```diff
@@ -144,6 +145,7 @@ export class ModalWrapperComponent
     .asObservable()
     .pipe(debounceTime(this.VIEWPORT_RESIZE_DEBOUNCE_TIME));
   private _mutationObserver: MutationObserver;
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: I guess this can be removed now?
```suggestion
```

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 14]
```diff
@@ -144,6 +145,7 @@ export class ModalWrapperComponent
...
+  private mutationObserverDisconnectFn: () => void;
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Consider naming - IMO it's an implementation detail what the return function actually does (unobserve, disconnect or something else)
```suggestion
  private unobserveFn: () => void;
```

File: libs/designsystem/helpers/src/content-mutation-observer.spec.ts [hunk 15]
```diff
@@ -0,0 +1,87 @@
...
+
+@Component({
+  // eslint-disable-next-line @angular-eslint/component-selector
+  selector: 'content-observer-host',
+  template: '<div [innerHtml]="content"></div>',
+})
+class ContentObserverHostComponent implements OnDestroy {
+  @Input() content: string = 'Initial content';
+
+  private mutationObserverDisconnectFn: () => void;
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.spec.ts]: Consider naming - IMO it's an implementation detail what the return function actually does (unobserve, disconnect or something else)

File: libs/designsystem/helpers/src/content-mutation-observer.ts [hunk 16]
```diff
@@ -0,0 +1,55 @@
...
+/**
+ * Creates a MutationObserver and observes content changes in a given element.
+ * The provided callback is called when changes are detected.
+ *
+ * @returns function - a disconnect function that can be called to disconnect the created observer.
+ */
+export function observeContent(
+  observedElement: HTMLElement,
+  contentChangedCallback: () => void
+): () => void {
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.ts]: Consider adding an explicit type like we have for `EventListenerDisposeFn` to hint the calling code it should do something with the returned function. Could be added to to the `types` lib
```suggestion
export function observeContent(
  observedElement: HTMLElement,
  contentChangedCallback: () => void
): UnobserveFn {
```

File: libs/designsystem/helpers/src/content-mutation-observer.ts [hunk 17]
```diff
@@ -0,0 +1,55 @@
...
+  }
+  // Observe everything else.
+  return false;
+}
+
+/**
+ * Creates a MutationObserver and observes content changes in a given element.
+ * The provided callback is called when changes are detected.
+ *
+ * @returns function - a disconnect function that can be called to disconnect the created observer.
```
Comment (jakobe) [inline libs/designsystem/helpers/src/content-mutation-observer.ts]:
```suggestion
 * @returns function - an unobserve function that can be called to disconnect the created observer.
```

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html [hunk 18]
```diff
@@ -37,7 +37,30 @@
     ...
 {{ '}' }}</cookbook-code-viewer>
   </p>
-  <h4>Alert config properties:</h4>
+
+  <h2>Accessibility</h2>
+  <p>
+    Alerts have a
+    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role">
+      dialog
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]: There's an accidental space somewhere in here: 
image

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts (hunk 14 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: I think the readability suffers if we omit the implementation details, as we have multiple observers going on in the code. 

We end up with something like this in the destroy hook, so I ended up going with a more explicit name. 
  ```
ngOnDestroy() {
  ...
    this.unobserveFn();
    this.intersectionObserver.disconnect();
    delete this._intersectionObserver;
    if (this.resizeObserverService) {
      this.resizeObserverService.unobserve(this.windowRef.nativeWindow.document.body);
      this.resizeObserverService.unobserve(this.ionHeaderElement.nativeElement);
      this.resizeObserverService.unobserve(this.currentFooter);
    }
   ...
  }
```

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html (hunk 18 above)
Comment (RasmusKjeldgaard) [reply apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]: Can't find it, can you help me locate it?

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html [hunk 19]
```diff
@@ -37,7 +37,30 @@
     ...
 {{ '}' }}</cookbook-code-viewer>
   </p>
-  <h4>Alert config properties:</h4>
+
+  <h2>Accessibility</h2>
+  <p>
+    Alerts have a
+    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role">
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]:
```suggestion
    <a href="https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role">dialog</a>
```

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html (hunk 18 above)
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]:
```suggestion
```

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html [hunk 20]
```diff
@@ -37,7 +37,30 @@
...
+      dialog
+    </a>
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]:
```suggestion
```

File: apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html (hunk 19 above)
Comment (Fuzzy3) [reply apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]: I dont know if this works 😋

Comment (RasmusKjeldgaard) [reply apps/cookbook/src/app/showcase/alert-showcase/alert-showcase.component.html]: I understand now! This is an issue we have because our prettier-config adds newlines for html tags, at least when above a certain amount of characters.

Added prettier-ignore and put it on one line as you suggested.

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 21]
```diff
@@ -621,8 +620,7 @@ export class ModalWrapperComponent
       this.routerOutlet.deactivate();
     }
     //clean up the observer
-    this.mutationObserverDisconnectFn();
-    delete this._mutationObserver;
+    this.mutationObserverUnobserveFn();
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Maybe make this a bit more resilient by either initializing the field with a noop `(private mutationObserverUnobserveFn: UnobserveFn = () => {};`) or:
```suggestion
    this.mutationObserverUnobserveFn?.();
```

Comment (RasmusKjeldgaard) [reply libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Great idea, thanks!

**Review by jakobe — DISMISSED** [review]

File: libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts [hunk 22]
```diff
@@ -75,6 +94,12 @@ export class ModalCompactWrapperComponent implements Modal, OnInit {
     }
   }
 
+  private setAriaLabelOnModal() {
+    if (this.ionModalElementDialog && this.ariaLabel) {
+      this.ionModalElementDialog.ariaLabel = this.ariaLabel;
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/modal/src/modal-wrapper/compact/modal-compact-wrapper.component.ts]: If we leave these changes in, remember so use `renderer.setAttribute` here.

File: libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts [hunk 23]
```diff
@@ -404,17 +404,29 @@ export class ModalWrapperComponent
...
 
+  private setAriaLabel() {
+    const ariaLabel = this.config.htmlAttributes?.['aria-label'];
+    const ionModalElementDialog = getIonModalDialogAncestor(this.ionModalElement);
+
+    if (ionModalElementDialog && ariaLabel) {
+      this.renderer.setAttribute(ionModalElementDialog, 'aria-label', ariaLabel);
+    } else {
+      this.observeTitleContentChanges();
+      this.setAriaLabelFromTitleContent();
```
Comment (jakobe) [inline libs/designsystem/modal/src/modal-wrapper/modal-wrapper.component.ts]: Really nitty gritty 🙈 😅, but somehow I think this would read better in reverse order, i.e. "set it, then observe"   
```suggestion
      this.setAriaLabelFromTitleContent();
      this.observeTitleContentChanges();
```

**Review by jakobe — APPROVED** [review]
🥳
