### PR TITLE
Range: add accessible name to kirby range

### LINKED ISSUE #3805: [BUG] Range: unable to add accessible name to kirby-range
- [X] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue)

## Describe the bug

There is an accessibility issue in the Kirby Range component where integrators are unable to add an accessible name. The name needs to be placed somewhere in the Shadow DOM. This cannot be fixed “outside” Kirby, therefore changes has to be made within the code base.

## Describe how to reproduce the bug
1. Use Kirby Range component
2. Use LevelAccess tool
3. See the error present itself through the tool:
4. Error: “Element with role ‘slider’ missing an accessible name”
 
## What was the expected behavior?
Expected slider component to be accessible out-of-the-box.

## Please complete the following information:
- OS: MacOS
- Browser Chrome

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Loujuu**
## Which issue does this PR close?

This PR closes #3805

## What is the new behavior?

Add accessible name to kirby range 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/range/src/range.component.ts [hunk 1]
```diff
@@ -30,6 +30,7 @@ import { IonRange } from '@ionic/angular/standalone';
 export class RangeComponent implements OnChanges, OnInit, ControlValueAccessor {
   @Input() minLabel: string;
   @Input() maxLabel: string;
+  @Input() ariaLabel: string;
```
Comment (Fuzzy3) [inline libs/designsystem/range/src/range.component.ts]: Instead of having basic html-attributes like aria-label and aria-labelledBy as angular inputs, we should use our utility class `label-helpers.ts` with the `forwardAttributes(...)` function to easily forward attributes from the host element to the internal ionic element. See radio-group for how this is done 🙏

File: libs/designsystem/range/src/range.component.html [hunk 2]
```diff
@@ -2,6 +2,7 @@
   (ionChange)="_onRangeValueChange($event)"
   [min]="min"
   [max]="max"
+  [attr.aria-label]="ariaLabel"
```
Comment (Fuzzy3) [inline libs/designsystem/range/src/range.component.html]: we should also support aria-labelledBy

File: apps/cookbook/src/app/examples/range-example/examples/default.component.ts [hunk 3]
```diff
@@ -3,7 +3,7 @@ import { RangeComponent } from '@kirbydesign/designsystem/range';
 
 const config = {
   selector: 'cookbook-range-default-example',
-  template: `<kirby-range minLabel="Min label" maxLabel="Max label" max="100" min="1" value="25"></kirby-range>`,
+  template: `<kirby-range minLabel="Min label" maxLabel="Max label" ariaLabel="Value" max="100" min="1" value="25"></kirby-range>`,
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/examples/range-example/examples/default.component.ts]: Nice to put an aria-label on the examples! May I suggest that we use a label that better describes the range itself. Maybe: "Default Range". The other examples could probably also use a more describing name.

**Review by Fuzzy3 — CHANGES_REQUESTED** [review]
Great ideas in this PR! In general I think we should use the label-helpers.forwardAttributes function instead of component inputs. Also we should support aria-labelledBy next to aria-label since we don't know which of these integrators might want to use. 
And then a few unit tests would probably be nice, to see that we actually manage to forward aria-label and aria-labelledBy from the host element to the ion-range element.  💪

File: libs/designsystem/range/src/range.component.ts (hunk 1 above)
Comment (Loujuu) [reply libs/designsystem/range/src/range.component.ts]: Great idea. I have removed aria-label and use utility class label-helper.ts

**Review by Fuzzy3 — APPROVED** [review]
This is some HIGH QUALITY WORK !! Nicely done !
