### PR TITLE
Use HashLocationStrategy for routing & make phone-previews HashLocationStrategy compatible

### LINKED ISSUE #1777: [BUG] Active branch deployment links do not redirect
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
In some situations (e.g. when accessing a link to a deployment from outside the github context - like pressing a link in slack) the cookbook.kirby.design/branch/**_some-branch_** link does not correctly match the route, and thus does not show the correct page. 

This is a result of the new github pages deploy workflow.

## Describe how to reproduce the bug

1. Try to access an active deployment link in Incognito mode or similar
2. See that page is blank, that url is cookbook.kirby.design (no branch) and the following error in console:
   - Error: Cannot match any routes. URL Segment: 'branch/**_branch-name_**/home/intro'

## Which Kirby version was used?
v3.0.14

## What was the expected behavior?
I get redirected to the cookbook app of my deployed branch, with my changes. 

## Are there any additional context?
This is most likely solved by using Hashbased Routing in our Angular cookbook app

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
~~- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". ~~
- [x] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [x] Create a pull-request.

### PR DESCRIPTION
**Pull request by MadsBuchmann**
## Which issue does this PR close?

This PR closes #1777

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Are there any additional context?

#1778 had already been merged to fix this but it had to be reverted in #1779 as it caused the iPhone previews to not work. 

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] ~~Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)"~~.
- [ ] ~~Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).~~

### Review  
- [X] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [X] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

### CODE REVIEW

File: apps/cookbook/src/app/iphone/iphone.component.ts [hunk 1]
```diff
@@ -38,4 +39,10 @@ export class IphoneComponent implements OnChanges, AfterViewInit {
     document.style.setProperty('--ion-safe-area-top', '20px');
     document.style.setProperty('--ion-safe-area-bottom', '22px');
   }
+
+  createTrustedSrc(unstrustedSrc: string) {
+    const src =
+      this.locationStrategy instanceof HashLocationStrategy ? `#${unstrustedSrc}` : unstrustedSrc;
+    return this.sanitizer.bypassSecurityTrustResourceUrl(src);
+  }
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/iphone/iphone.component.ts:47]: VERY NICE! :kirby-dancing:

**Review by RasmusKjeldgaard — APPROVED** [review]
