### PR TITLE
Menu: Items added after creation of menu also gets selected set to true

### LINKED ISSUE #4168: [BUG] Extra click needed if menu items exists within an if-condition or in a for-loop in a menu
## Describe the bug
When using the menu component I have found that, if the items within the menu are in an if-condition or build using a for-loop, like this:
```
<kirby-menu>
  @for(item of elements; track $index;) {
    <kirby-item>            
      <kirby-icon name="add" slot="start" />
      {{item}}                               
    </kirby-item>
  }
</kirby-menu>
```
the menu requires an extra click when opened before the items become selectable.

## Describe how to reproduce the bug
1. Have a menu with items that are conditionally shown
2. Click the menu -> notice how the items are not showing a hover effect on mouse over
3. Click an item -> notice how the item is not clicked, however the items now have the hover effect
4. The items are now clickable

## Which Kirby version was used?
11.4.0

## What was the expected behavior?
Single click should be enough 😉 

## Are there any additional context?
I found that a quick-fix exist if I put `selectable="true"` on each item.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Fuzzy3**
## Which issue does this PR close?

This PR closes #4168 

## What is the new behavior?
Subscribing to changes from the `ContentChildren` for kirby items, and if there are changes, then re-run a function that adds the `selectable=true` input on `kirby-item`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/menu/src/menu.component.ts [hunk 1]
```diff
@@ -117,7 +123,7 @@ export class MenuComponent implements AfterViewInit, AfterContentInit, OnDestroy
     }
   }
 
-  @HostListener('click', ['$event'])
+  @HostListener('click')
```
Comment (Fuzzy3) [inline libs/designsystem/menu/src/menu.component.ts:124]: Boy scouting 🫡

File: libs/designsystem/menu/src/menu.component.spec.ts [hunk 2]
```diff
@@ -286,6 +286,53 @@ describe('MenuComponent', () => {
...
+        { hostProps: { show: false } }
+      );
+      buttonElement = spectator.query('button');
+      spectator.setHostInput({ show: true });
+      await spectator.click(buttonElement);
+      spectator.detectChanges();
+      const ionItem = spectator.query('ion-item');
+      await TestHelper.whenReady(ionItem);
+      const selectableIonItem = ionItem.shadowRoot.querySelector('button'); //"button" only exist if item is selectable
+      expect(selectableIonItem).toBeTruthy();
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.spec.ts]: Consider readability by using some whitespace to signal AAA pattern:

```suggestion
      buttonElement = spectator.query('button');
      spectator.setHostInput({ show: true });
      
      await spectator.click(buttonElement);
      spectator.detectChanges();
      
      const ionItem = spectator.query('ion-item');
      await TestHelper.whenReady(ionItem);
      const selectableIonItem = ionItem.shadowRoot.querySelector('button'); //"button" only exist if item is selectable
      
      expect(selectableIonItem).toBeTruthy();
```

File: libs/designsystem/menu/src/menu.component.spec.ts [hunk 3]
```diff
@@ -286,6 +286,53 @@ describe('MenuComponent', () => {
...
+        `<kirby-menu>
+          @if (show) {
+            <kirby-item>
+              <p>Action 1</p>
+            </kirby-item>
+          }
+        </kirby-menu>`,
+        { hostProps: { show: false } }
+      );
+      buttonElement = spectator.query('button');
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.spec.ts]: Could this be more readable with buttonElement renamed to triggerButton or similar?

File: libs/designsystem/menu/src/menu.component.spec.ts [hunk 4]
```diff
@@ -286,6 +286,53 @@ describe('MenuComponent', () => {
     });
   });
 
+  describe('interaction with items in condition', () => {
+    it('should select item when clicked when wrapped in if statement', async () => {
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.spec.ts]:
```suggestion
  describe('interaction with items that are conditionally shown', () => {
    it('should select item inside if statement', async () => {
```

File: libs/designsystem/menu/src/menu.component.spec.ts [hunk 5]
```diff
@@ -286,6 +286,53 @@ describe('MenuComponent', () => {
...
+      spectator.setHostInput({ show: true });
+      await spectator.click(buttonElement);
+      spectator.detectChanges();
+      const ionItem = spectator.query('ion-item');
+      await TestHelper.whenReady(ionItem);
+      const selectableIonItem = ionItem.shadowRoot.querySelector('button'); //"button" only exist if item is selectable
+      expect(selectableIonItem).toBeTruthy();
+    });
+
+    it('should select item when clicked when wrapped in for loop', async () => {
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.spec.ts]:
```suggestion
    it('should select item in for loop', async () => {
```

File: libs/designsystem/menu/src/menu.component.spec.ts [hunk 6]
```diff
@@ -286,6 +286,53 @@ describe('MenuComponent', () => {
...
+      );
+      buttonElement = spectator.query('button');
+      spectator.setHostInput({ show: true });
+      await spectator.click(buttonElement);
+      spectator.detectChanges();
+      const ionItems = spectator.queryAll('ion-item');
+      const firstIonItem = ionItems[0];
+      await TestHelper.whenReady(firstIonItem);
+      const selectableIonItem = firstIonItem.shadowRoot.querySelector('button'); //"button" only exist if item is selectable
+      expect(selectableIonItem).toBeTruthy();
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.spec.ts]: Consider AAA here too:
```suggestion
      buttonElement = spectator.query('button');
      spectator.setHostInput({ show: true });
      
      await spectator.click(buttonElement);
      spectator.detectChanges();
      
      const ionItems = spectator.queryAll('ion-item');
      const firstIonItem = ionItems[0];
      await TestHelper.whenReady(firstIonItem);
      const selectableIonItem = firstIonItem.shadowRoot.querySelector('button'); //"button" only exist if item is selectable
      
      expect(selectableIonItem).toBeTruthy();
```

File: libs/designsystem/menu/src/menu.component.ts [hunk 7]
```diff
@@ -43,6 +47,8 @@ export class MenuComponent implements AfterViewInit, AfterContentInit, OnDestroy
   triggerButtonId: string = UniqueIdGenerator.scopedTo('kirby-menu-trigger-button').next();
   private _attributesToForward = ['aria-label', 'aria-labelledby'];
 
+  private destroyRef = inject(DestroyRef);
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.ts]: Love the idea of using inject function but consider using constructor based injection for now to avoid mixing the approach within same file.

**Review by RasmusKjeldgaard — COMMENTED** [review]
Nice! 👏

File: libs/designsystem/item/src/item.component.ts [hunk 8]
```diff
@@ -43,7 +44,14 @@ export class ItemComponent implements AfterViewInit {
...
   disclosure: 'link' | 'arrow-more' | 'arrow-down' | 'arrow-up' | null;
-  @Input() selectable: boolean;
+  @Input() set selectable(value: boolean) {
+    this._selectable = value;
+    this.cdr.markForCheck();
+  }
+  get selectable(): boolean {
+    return this._selectable;
+  }
+  private _selectable: boolean;
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/item/src/item.component.ts]: Ahh, missed this one before, but consider making this a bit easier to read, and follow the structure from segmented control, theme color directive etc.

```suggestion

  private _selectable: boolean;
  get selectable(): boolean {
    return this._selectable;
  }
  
  @Input() set selectable(value: boolean) {
    this._selectable = value;
    this.cdr.markForCheck();
  }
```

**Review by RasmusKjeldgaard — APPROVED** [review]
