### PR TITLE
Action Group: keep disabled state of action group buttons when collapsed

### LINKED ISSUE #3924: [BUG] Disabled buttons are enabled when collapsed into a "more menu"
## Describe the bug
We have three buttons in a "kirby-action-group"
If any of these buttons are disabled, they will become enabled when the buttons collapse into a more menu.
We also have a text showing when hovering the disabled button. This text is also shown when the button is collapsed (shown permanently and not only when hovered).

## Describe how to reproduce the bug
The page is currently under a feature toggle. Let us know if you need to access it. 
The MF is: ikv-mf-annual-investment-costs

## Which Kirby version was used?
   "@kirbydesign/designsystem": "10.3.1",

## What was the expected behavior?
I expected the button to still be disabled and the text to only be shown when hovered over the disabled button

## Add any screenshots

Image
Image

## Please complete the following information:
- OS:  Windows (WSL ubuntu)
- Browser: Edge
- Browser version: 136.0.3240.50

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Fuzzy3**
## Which issue does this PR close?

This PR closes #3924 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: apps/cookbook/src/app/examples/header-example/examples/action-group.ts [hunk 1]
```diff
@@ -11,12 +11,12 @@ import { BasePageExampleComponent } from '../../page-example/base-page-example.c
...
   template: `<kirby-page defaultBackHref="/">
   <kirby-header [title]="'Action Group'" subtitle1="Subtitle one" subtitle2="Subtitle two">
-    <kirby-action-group *kirbyHeaderActions>
+    <kirby-action-group *kirbyHeaderActions [visibleActions]="3">
       <button kirby-button attentionLevel="3" (click)="actionClicked('Action 1')">
         <kirby-icon name="edit"></kirby-icon>
         <span class="text">Action 1</span>
       </button>
-      <button kirby-button attentionLevel="3" (click)="actionClicked('Action 2')">
+      <button kirby-button attentionLevel="3" (click)="actionClicked('Action 2')" [disabled]="disabled">
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/header-example/examples/action-group.ts]:
```suggestion
      <button kirby-button attentionLevel="3" (click)="actionClicked('Action 2')" [disabled]="true">
```

Consider not changing visibleActions here, as this is the default example for action group, and I think we should keep it as simple as possible.

Consider adding a separate example, or alternatively validate the behavior with visual and unit testing, and then just write out that buttons can be disabled 😊

**Review by RasmusKjeldgaard — COMMENTED** [review]
Good job! 👏

File: apps/cookbook/src/app/examples/header-example/examples/action-group.ts (hunk 1 above)
Comment (Fuzzy3) [reply apps/cookbook/src/app/examples/header-example/examples/action-group.ts]: I think that the disabled state is such a normal thing to expect - that we don't need an example to prove it. I have decided to test it by unit testing

**Review by RasmusKjeldgaard — APPROVED** [review]
