### PR TITLE
Form Field: cannot focus input programmatically immediately after disabled state is removed

### LINKED ISSUE #3302: [BUG] Cannot focus input programmatically immediately after setting disabled to false
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If I try to replicate the example on the cookbook page for focusing programmatically on an input field within a form field, the input field is not focussed after the input field becomes enabled.

## Describe how to reproduce the bug
The bug can be reproduced by using the code from the cookbook snippets: 

```html
<kirby-checkbox
  [checked]="inputEnabled"
  (checkedChange)="onToggleInput($event)"
  text="Enable input">
</kirby-checkbox>

<kirby-form-field #formfield>
  <input kirby-input [size]="size" [disabled]="!inputEnabled" placeholder="Enable to focus (+scroll into view on device)" />
</kirby-form-field>
```

```ts
import { FormFieldComponent } from '@kirbydesign/designsystem';
  
export class MyComponent {
  @ViewChild('formfield') private formfield: FormFieldComponent;

  inputEnabled = false;

  onToggleInput(enable: boolean) {
    this.inputEnabled = enable;
    if (!enable) return;
    this.formfield.focus();
  }
}
```

The above example is not what is actually happening in the example on https://cookbook.kirby.design/#/home/showcase/form-field - in the code running in the browser we actually do 
`setTimeout(() => this.formfield.focus());`

We should either fix the documentation or move the setTimeout call to our internal implementation so consumers do not have to worry.

## Which Kirby version was used?
8.11.2

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3302 

## What is the new behavior?
We take care of the `setTimeout` when focussing nested input element in form field, instead of relying on consumers to do so.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/form-field/src/form-field.component.ts [hunk 1]
```diff
@@ -89,18 +89,24 @@ export class FormFieldComponent
...
-      this.inputElement.dispatchEvent(touchEnd);
-    } else {
-      this.inputElement.focus();
-    }
+    /*
+     * This timeout ensures that any previous manipulation of inputElement
+     * (e.g. setting disabled state) has been synced to the DOM before trying to focus.
+     */
+    setTimeout(() => {
+      if (!this.inputElement) return;
```
Comment (jakobe) [inline libs/designsystem/form-field/src/form-field.component.ts]: Maybe leave this guard outside the timeout for readability? 🤔

**Review by jakobe — DISMISSED** [review]
1 small comment, not a biggie, leave it up to you to decide 😊

File: libs/designsystem/form-field/src/form-field.component.ts (hunk 1 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/form-field/src/form-field.component.ts]: Good idea, done!

**Review by jakobe — APPROVED** [review]
