### PR TITLE
Enhancement/avatar scaling fix

### LINKED ISSUE #299: [Enhancement] Avatar scaling not needed (right now)
**Is your enhancement request related to a problem? Please describe.**
Our avatars scale (get bigger) on bigger screensizes. This is not actually a feature we need (right now) :) Our avatars stay the same on all screensizes.

Maybe this could be a property to turn on/off?

### PR DESCRIPTION
**Pull request by jb-trm**
Removed responsive scaling of the avatar component.

Removed the xlarge option.

https://app.zeplin.io/project/5c99d69a79d02b35ea3b8f41/styleguide/components?coid=5c9bd0ff16d4ed776bb28bdb

closes #299

### CODE REVIEW

File: src/app/showcase/avatar-showcase/avatar-showcase.component.ts [hunk 1]
```diff
@@ -8,7 +10,40 @@ declare var require: any;
...
+      name: 'imageSrc',
+      description: 'Points to the src of the image location',
+      defaultValue: 'null',
+      inputValues: ['string'],
+    },
+    {
+      name: 'size',
+      description: 'Sets the size of the button.',
+      defaultValue: 'null',
+      inputValues: ['sm', 'md', 'lg'],
```
Comment (jb-trm) [inline src/app/showcase/avatar-showcase/avatar-showcase.component.ts]: Wrong values

File: src/app/showcase/avatar-showcase/avatar-showcase.component.ts [hunk 2]
```diff
@@ -8,7 +10,40 @@ declare var require: any;
...
+      name: 'imageSrc',
+      description: 'Points to the src of the image location',
+      defaultValue: 'null',
+      inputValues: ['string'],
+    },
+    {
+      name: 'size',
+      description: 'Sets the size of the button.',
+      defaultValue: 'null',
+      inputValues: ['small', 'medium', 'large'],
```
Comment (hafstad) [inline src/app/showcase/avatar-showcase/avatar-showcase.component.ts]: Use sizes from size directive to avoid hardcoded sizes: 
import { Sizes } from '@kirbydesign/designsystem/directives/size/size.directive';
Object.values(this.sizes)
