### PR TITLE
Dropdown: close dropdown on click outside

### LINKED ISSUE #4142: [BUG]  When dropdown is expanded and user clicks outside the dropdown it does not close
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Wanted behavior: Close the dropdown on click outside dropdown.  

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Loujuu**
## Which issue does this PR close?

This PR closes #4142 

## What is the new behavior?

If dropdown is open, when click outside, the dropdown should close.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/dropdown/src/dropdown.component.ts [hunk 1]
```diff
@@ -405,6 +405,8 @@ export class DropdownComponent implements AfterViewInit, OnDestroy, ControlValue
     }
   }
 
+  private documentClickListener: (() => void) | null = null;
```
Comment (Fuzzy3) [inline libs/designsystem/dropdown/src/dropdown.component.ts]: consider using the type: EventListenerDisposeFn

File: libs/designsystem/dropdown/src/dropdown.component.spec.ts [hunk 2]
```diff
@@ -673,13 +673,6 @@ describe('DropdownComponent', () => {
         });
       });
 
-      describe('and looses focus', () => {
```
Comment (Fuzzy3) [inline libs/designsystem/dropdown/src/dropdown.component.spec.ts:676]: Leave in the unit tests, but test on the blur event from the button instead of the host

**Review by Fuzzy3 — CHANGES_REQUESTED** [review]
Lets update the unit tests to test the blur event on the button, instead of removing the tests

File: libs/designsystem/dropdown/src/dropdown.component.stories.ts [hunk 3]
```diff
@@ -69,6 +69,31 @@ export const Dropdown: Story = {
...
+        Outside Close
+      </button>
+    `,
+  }),
+  play: async ({ canvasElement }) => {
+    const canvas = within(canvasElement);
+
+    const toOpen = canvas.getByRole('combobox');
+    await userEvent.click(toOpen);
+
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/dropdown/src/dropdown.component.stories.ts:95]: Can we do something here programmatically to verify that the dropdown is in fact open?

File: libs/designsystem/dropdown/src/dropdown.component.spec.ts [hunk 4]
```diff
@@ -675,7 +675,13 @@ describe('DropdownComponent', () => {
 
       describe('and looses focus', () => {
         it('should close dropdown', () => {
-          spectator.dispatchFakeEvent(spectator.element, 'blur');
+          const buttonElement = spectator.query('button[kirby-button]');
+          spectator.component.open();
+          spectator.detectChanges();
+
```
Comment (Fuzzy3) [inline libs/designsystem/dropdown/src/dropdown.component.spec.ts]: No need to open the dropdown, its already open at this point, caused by the wrapping describe

File: libs/designsystem/dropdown/src/dropdown.component.spec.ts [hunk 5]
```diff
@@ -1091,8 +1097,11 @@ describe('DropdownComponent', () => {
       it('should invoke callback from registerOnTouched() function on blur', () => {
         const onTouchedSpy = jasmine.createSpy('_onTouched');
         spectator.component.registerOnTouched(onTouchedSpy);
-        spectator.blur();
+
+        const buttonElement = spectator.query('button[kirby-button]');
+        buttonElement.dispatchEvent(new FocusEvent('blur'));
```
Comment (Fuzzy3) [inline libs/designsystem/dropdown/src/dropdown.component.spec.ts:1097]: is it not possible to do something like buttonElement.blur?

**Review by Fuzzy3 — CHANGES_REQUESTED** [review]
Almost there, just a few nittys about the unit tests

**Review by Fuzzy3 — APPROVED** [review]
