### PR TITLE
Fix kirby-radio-group error

### LINKED ISSUE #1476: Kirby-radio-group throws an error
**Describe the bug**

When using a `kirby-radio-group`, an error is thrown/logged in the console and an error toast appears.
The error occurs when selecting/clicking a `kirby-radio` item and then clicking somewhere random on the page.
See screenshot of error:
Screenshot 2021-04-19 at 13 42 22

The error started occurring after creating a new branch from master. I did a reinstall of node_modules but it did not fix the error.

**To Reproduce**

Using the simplest example from cookbook on a random DRB page results in the error:
<kirby-radio-group [items]="['Bacon', 'Salami', 'Tenderloin']"></kirby-radio-group> 

**Kirby version**
- [1.4.32]

**Expected behavior**

**Screenshots**
Screenshot 2021-04-19 at 13 42 22

**Please complete the following information:**
- OS: MacOS
- Browser Chrome

**Additional context**

## Tasks:
- [x] Have the bug report verified by contacting a member of @kirbydesign/kirby-guild
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

### PR DESCRIPTION
**Pull request by jkaltoft**
This PR closes #1476

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement (to existing content)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## Which issue documents the current behaviour?

Issue Number: #1476

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Before

https://user-images.githubusercontent.com/150451/115281524-6559ca80-a149-11eb-8350-88bc92e66e12.mov

### After

https://user-images.githubusercontent.com/150451/115281549-6db20580-a149-11eb-9248-41b7da0c0d03.mov

### CODE REVIEW

File: libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.ts [hunk 1]
```diff
@@ -99,7 +100,7 @@ export class RadioGroupComponent implements AfterContentInit, ControlValueAccess
   private _disabled = false;
   private _items: string[] | any[] = [];
   private _onChangeCallback: (value: any) => void = () => {};
-  private _onTouched: Function;
+  private _onTouched = noop;
```
Comment (jakobe) [inline libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.ts:103]: Why the extra abstraction using noop from RxJS compared to just inlining a noop function?
And why differ from the implementation in dropdown?
```suggestion
  private _onTouched = () => {};
```

Comment (jkaltoft) [reply libs/designsystem/src/lib/components/radio/radio-group/radio-group.component.ts:103]: I think a named function like `noop` is more explicit about "nothing is going to happen" (even though it's a minor difference in this case). If it's `()  => {}` in the dropdown implementation we should go with that here as well.

**Review by hafstad — APPROVED** [review]
