### PR TITLE
Fix popovers hide() being called twice

### LINKED ISSUE #2180: [BUG] popovers hide() function is called twice on dropdown-item click
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
For a dropdown configured with `[usePopover]="true"`, popovers `hide()` is called twice whenever an item in the dropdown is clicked. 

This has caused issues for consumers, that see errors like below for subsequent calls to hide(), when dropdown is already hidden:

```
uncaught error in micro frontend DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at EmulatedEncapsulationDomRenderer2.removeChild (http://localhost:8783/default-node_modules_bankdata_relationsbank-sdk_fesm2015_bankdata-relationsbank-sdk-micro-fro-4d56c1.js:51308:20)
    at PopoverComponent.hide (http://localhost:8783/default-node_modules_bankdata_relationsbank-sdk_fesm2015_bankdata-relationsbank-sdk-micro-fro-4d56c1.js:84125:23)
    at PopoverComponent._backdropClick (http://localhost:8783/default-node_modules_bankdata_relationsbank-sdk_fesm2015_bankdata-relationsbank-sdk-micro-fro-4d56c1.js:84072:14)
    at PopoverComponent_click_HostBindingHandler (http://localhost:8783/default-node_modules_bankdata_relationsbank-sdk_fesm2015_bankdata-relationsbank-sdk-micro-fro-4d56c1.js:84181:141)
```

## Describe how to reproduce the bug
1. Check out repo, and edit a dropdown in the cookbook example to have `[usePopover]="true"`.
2. debug with breakpoint on popovers `hide()` function or `console.log` something in the function.
3. See it being called twice, when an item within the dropdown is clicked.

## Which Kirby version was used?
5.2.2

## What was the expected behavior?
Only call `hide()` once, as the DOM is manipulated in the function, and elements might not be present on subsequent calls when the dropdown has been hidden.

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?
The reason that the function is called twice, is that a backdrop click is also recorded, due to the hostlistener in popover: 
https://github.com/kirbydesign/designsystem/pull/1671/commits/51f8d12a563fd6207c3f97f63fcf896416f36d26#diff-0f54fa478d78f29a82f9c3830d735d4c5de57f30cf649945ea9d7c51fc0d2db8R48-R52

Unfortunately, the HostListener is added as part of a very large commit, so not much history exist on why it was added. It does not seem to fire when clicking the backdrop(!) and generally the popover functionality seems to work without it, at least when used in a dropdown. 

Would be interesting to investigate if the listener can be removed entirely, if it is leftover functionality accidentally left in the component. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/stable/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [stable branch](https://github.com/kirbydesign/designsystem/tree/stable) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #2180 

## What is the new behavior?
The hide functionality has been refactored a bit to ensure that the element is in fact showing, before doing hide logic.

Furthermore, the backdropClick listener was removed, because it was not functional, as described in the commit message: 

> The event listener was not called because dropdowns onBlur event was
> always fired first, closing the dropdown including the popover
> component. In fact it was only called when clicking inside the dropdown
> because onBlur is not fired then - and thus it is useless at this point.
> 
> Components using popover (dropdown only right now) should take care of
> calling hide() at the appropriate time themselves, e.g. in onBlur.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/stable/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to `stable` via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

### CODE REVIEW

**Comment by RasmusKjeldgaard** [comment]
@andershessellund has checked that this works in the target application

File: libs/designsystem/src/lib/components/popover/popover.component.ts [hunk 1]
```diff
@@ -56,16 +56,9 @@ export class PopoverComponent implements AfterViewInit, OnDestroy {
...
 
-  @HostListener('click')
-  _backdropClick() {
-    this.willHide.emit();
-    this.hide();
-  }
-
   @HostListener('window:resize')
   _onWindowResize() {
     if (this.isShowing) {
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/popover/popover.component.ts:61]: This check seems a bit redundant when we have the check in  hide :)

**Review by MadsBuchmann — CHANGES_REQUESTED** [review]
teeny tiny comment - otherwise lgtm!
