### PR TITLE
Fix item-selection on dropdown with popover in safari

### LINKED ISSUE #2317: [BUG] UsePopover iOS
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
UsePopover is not working correctly on iOS. 
When selecting an element in a dropdown (with usePopover="true") on iOS, the dropdown just closes without selecting or emitting the selected element.

It works fine when used on a calendar component though

## Which Kirby version was used?
5.4.1

## Please complete the following information:
- OS: [iOS]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by mictro**
## Which issue does this PR close?

This PR closes #2317

## What is the new behavior?

Fix selection problem on dropdown with popover in Safari/WebView.

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [X] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [X] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [X] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [X] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/src/lib/components/dropdown/dropdown.component.ts [hunk 1]
```diff
@@ -471,14 +471,19 @@ export class DropdownComponent
 
   @HostListener('keydown.enter')
   @HostListener('keydown.escape')
+  _onEnterOrEsscape(event?: FocusEvent) {
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/dropdown/dropdown.component.ts:474]:
```suggestion
  _onEnterOrEscape(event?: FocusEvent) {
```

Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/dropdown/dropdown.component.ts:474]: I'm getting the following linting error on this line:
```[tsserver 6133] [I] 'event' is declared but its value is never read.```

File: libs/designsystem/src/lib/components/dropdown/dropdown.component.ts [hunk 2]
```diff
@@ -471,14 +471,19 @@ export class DropdownComponent
...
+    this.close();
+    this._onTouched();
+  }
+
+  _onPopoverClick(event: PointerEvent) {
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/dropdown/dropdown.component.ts:479]: I'm getting the following linting error on this line:
```[tsserver 6133] [I] 'event' is declared but its value is never read.```

File: libs/designsystem/src/lib/components/dropdown/dropdown.component.ts [hunk 3]
```diff
@@ -471,14 +471,19 @@ export class DropdownComponent
...
+    this.close();
+  }
+
   @HostListener('blur', ['$event'])
   _onBlur(event?: FocusEvent) {
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/dropdown/dropdown.component.ts:484]: I'm getting the following linting error on this line:
```[tsserver 6133] [I] 'event' is declared but its value is never read.```

**Review by MadsBuchmann — CHANGES_REQUESTED** [review]
Got some minor comments and it seems like there are failing tests. 

In the long run i really think we should be looking into using ionics popover functionality instead of our own homebrewed concoction.

**Review by MadsBuchmann — APPROVED** [review]
LGTM!
