### PR TITLE
fix(slide-button): removing leaking timers

### LINKED ISSUE #822: [BUG] Slide button lags
**Describe the bug**
Slide button lags after having slided a couple of times

**To Reproduce**

Slide to almost 100% a couple of times on a mobile screen.

Only on mobile! (due to mousedown not being triggered)
1. Go to 'Slide button' in cookbook
2. Slide a couple of time to 90%
4. See that it now will lag and toggle between current slider thumb position and 0

**Kirby version**

- [e.g. 0..8.51]

**Expected behavior**

It should not lag when sliding.

**Screenshots**

**Please complete the following information:**
This will be a problem on all mobile platforms + browser running as simulated mobile.
- OS: Windows, MacOS, iOS
- Browser Chrome, mobile view
- Version 78.0.3904.108

### PR DESCRIPTION
**Pull request by lydemann**
Closes #822
Fix leaking interval when resetting slide.

### CODE REVIEW

File: src/kirby/components/page/page.component.ts [hunk 1]
```diff
@@ -105,10 +105,6 @@ export class PageComponent implements OnInit, OnDestroy, AfterViewInit, AfterCon
   @ViewChild(IonContent, { static: true }) private content: IonContent;
   @ViewChild('pageTitle', { static: false, read: ElementRef })
   private pageTitle: ElementRef;
-  @ViewChild('stickyToolbarButtons', { static: false, read: ElementRef })
-  private stickyToolbarButtons: ElementRef;
-  @ViewChild('fixedToolbarButtons', { static: false, read: ElementRef })
-  private fixedToolbarButtons: ElementRef;
   @ViewChild('simpleTitleTemplate', { static: true, read: TemplateRef })
```
Comment (lydemann) [inline src/kirby/components/page/page.component.ts]: Just cleaned up the unused. Don't worry :)

Comment (jakobe) [reply src/kirby/components/page/page.component.ts]: I _do_ get worried... Boyscouting should be done in relation to something you're already fixing/improving/cleaning up, not something completely unrelated... Please revert and keep focus on the thing you're trying to fix 👍

File: src/kirby/components/page/page.component.ts [hunk 2]
```diff
@@ -119,8 +115,6 @@ export class PageComponent implements OnInit, OnDestroy, AfterViewInit, AfterCon
   customTitleTemplate: TemplateRef<any>;
   @ContentChildren(PageActionsDirective)
   customActions: QueryList<PageActionsDirective>;
-  @ContentChild(PageActionsComponent, { static: false })
```
Comment (jakobe) [inline src/kirby/components/page/page.component.ts]: Same as above
