### PR TITLE
Fix dead links on "tabs" and "list" pages

### LINKED ISSUE #1282: [BUG] Some "example on github"-links are dead
**Describe the bug**

On the cookbook example pages for the list component, clicking on the "example on github" button sends you to githubs 404 page. 

**To Reproduce**

1. Go to one of the following pages: 

- https://cookbook.kirby.design/home/showcase/list
- https://cookbook.kirby.design/home/showcase/list-load-on-demand
- https://cookbook.kirby.design/home/showcase/list-swipe
- https://cookbook.kirby.design/home/showcase/list-no-shape
- https://cookbook.kirby.design/home/showcase/reorder-list
- https://cookbook.kirby.design/home/showcase/tabs

2. Click on 'example on github'
3. You should see githubs 404 page. 

**Kirby version**
- 1.4.1

**Expected behavior**
Clicking the button  should take me to the code on github, as it does on the action-sheet component page (https://cookbook.kirby.design/home/showcase/action-sheet).

**Please complete the following information:**
- OS: MacOS
- Browser: Firefox
- Browser version: 85.0

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [x] Fix
- [x] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [x] Push commits to GitHub
- [x] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

### PR DESCRIPTION
**Pull request by MadsBuchmann**
This PR closes #1282

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #1282 

## What is the new behavior?
The "example on github"-links should work on all pages mentioned in the original issue. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information
I have seperated out the examples from the list folder as these were nested and resulted in dead links. While i can see why it would be done like this, it breaks the "example on github"-links. The new folder structure aligns more with the actual menu displayed in the cookbook, and allows the links to function. 

If the menu is at some point expanded to support nested menu items; i think the showcase component (showcase.component.ts) should be expanded, such that subfolders can be included in the "example on github"-links

### CODE REVIEW

File: apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts [hunk 1]
```diff
@@ -1,9 +1,10 @@
 import { Component } from '@angular/core';
 import { of } from 'rxjs';
 
-import { BaseListComponent } from '../base-list.component';
 import { LoadOnDemandEvent } from '@kirbydesign/designsystem';
 
+import { BaseListComponent } from './base-list.component';
```
Comment (jakobe) [inline apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts:6]: Why the need for the duplicated `BaseListComponent? 🤔

**Review by jakobe — COMMENTED** [review]
LGTM!
Just 1 minor thing :)

File: apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts (hunk 1 above)
Comment (MadsBuchmann) [reply apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts:6]: I wanted to keep each folder with examples self-contained 🎁

The `list-load-on-example-component` and the examples that are now found in `list-example/components/...`  initially pointed to the same `base-list.component`, as both were contained in the same parent folder. When splitting up the original `list`-folder, i did not want the `list-load-on-demand` example to depend on files in the `list-example`-folder. Therefore i created a duplicate.

It might however make more sense to just copy the data in `list-load-on-demand-example/base-list.component` directly into the `list-load-on-demand-example.component`-file. Might just muddy the file a bit, but it is done like that in the other list examples that are not located in the `list-example`-folder.

Comment (jakobe) [reply apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts:6]: Consider moving the file to a shared location instead 🤔

Comment (MadsBuchmann) [reply apps/cookbook/src/app/examples/list-load-on-demand-example/list-load-on-demand-example.component.ts]: As discussed on Slack with the new commit duplicates has been removed and baseListComponent is now stored in a list-shared folder 🗂 Should resolve comment.

**Review by jakobe — DISMISSED** [review]
Consider aligning name of examples subfolder as we do everywhere else:
`list-example\components` => `list-example\examples`

**Review by jakobe — APPROVED** [review]
🎉
