### PR TITLE
Image Banner: set height explicitly to preserve scroll state in safari

### LINKED ISSUE #3810: [BUG] Scroll state of kirby-page not preserved when using image-banner in Safari
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
In Safari, when navigating back to a page with a`kirby-x-image-banner`, scroll state is not preserved correctly. Even though we use `inline-size` for the container-query in `image-banner`, the height does not seem to be correctly calculated for the element when returning back to a page in the stack of an `ion-router-outlet`. I am unsure if this is a safari + containment issue or if it is a ion-router-outlet + safari + containment issue 🤷 

## Describe how to reproduce the bug

1. Go to https://stackblitz.com/edit/stackblitz-starters-3jbke7cs in safari. See * below if this does not work.
2. Scroll to the bottom of the page, click 'Go to Page Two', then press the back-button of the new page.
3. Observe that 'Page One' is scrolled all the way to the top. In chromium-browsers, previous scroll state is preserved and you land at the bottom of the page instead.

___

\* Safari and stackblitz does not always play nice. If the example never loads, do the following instead:
1. Click on the small "cloud + arrow down" icon to download the example. This is currently needed because stackblitz preview and safari does not play nice.
2. run `npm i && npm start` locally
3. go to localhost in Safari

## Which Kirby version was used?
Kirby Extensions v1.3.0

## Add any screenshots
Heres a video showcasing the issue: 

https://github.com/user-attachments/assets/4d40a9e6-a955-4139-9a78-9648e83df380

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3810 

## What is the new behavior?
See issue for background.
Scroll state is now preserved because the image-banner has explicit height set.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/extensions/angular/image-banner/src/image-banner-height.directive.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+  private setCardHeightOnHost(entry: ResizeObserverEntry) {
+    const hostElement = entry.target as HTMLElement;
+    const card = hostElement.querySelector('kirby-card');
+    const cardHeight = card?.getBoundingClientRect().height;
+
+    if (!hostElement || !cardHeight) return;
+    if (cardHeight === this.currentHeight) return;
+
+    this.currentHeight = cardHeight;
+    hostElement.style.minHeight = `${this.currentHeight}px`;
```
Comment (RasmusTraeholt) [inline libs/extensions/angular/image-banner/src/image-banner-height.directive.ts]: Consider using Renderer2 to manipulate the element's style instead

File: libs/extensions/angular/image-banner/src/image-banner.component.scss [hunk 2]
```diff
@@ -71,7 +69,8 @@ $container-query-breakpoint: 600px;
 }
 
 kirby-card {
-  height: 100%;
```
Comment (RasmusTraeholt) [inline libs/extensions/angular/image-banner/src/image-banner.component.scss:74]: height: 100% is needed for the `slideStretchHeight` directive to function and should not be removed

**Review by RasmusTraeholt — DISMISSED** [review]

**Review by RasmusTraeholt — APPROVED** [review]
