### PR TITLE
Menu: Add role to native input or button within item

### LINKED ISSUE #4159: [BUG] Screen reader not focussing menu when opened on Iphone or sometimes safari
## Describe the bug
When using a screen reader the content of a menu is not focussed, when the menu is opened. Thus it is not possible for screen reader users to navigate the items within the opened dropdown. 

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Fuzzy3**
## Which issue does this PR close?

This PR closes #4159 

## What is the new behavior?
VoiceOver needs the role attribute to be placed on the actual control (input/button), and not on the KirbyItem, to work. We pierce through the shadowdom of IonItem and find the native button (if its a selectable item) or input (if its an item with a checkbox or toggle) for each item in the menu and correctly adds the `role="menuitem` or `role=menuitemcheckbox` on the DOM element.  

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by RasmusKjeldgaard — COMMENTED** [review]
I played around with this, and it seems that we can avoid these changes if we simply add the menuitem role to the correct element (the one that the user is actually interacting with), like so:

```
import { componentOnReady } from '@ionic/core';

...

private async setRoleForItemNativeButton(item: HTMLElement) {
    const ionItem = item.querySelector<HTMLIonItemElement>('ion-item');
    if (!ionItem) return;

    let menuItemRole = 'menuitem';
    if (item.matches(':has(kirby-toggle, kirby-checkbox)')) {
      menuItemRole = 'menuitemcheckbox';
    } else if (item.matches(':has(kirby-radio)')) {
      menuItemRole = 'menuitemradio';
    }

    // Wait for ion-item to be hydrated before accessing Shadow DOM
    await new Promise<void>((resolve) => {
      componentOnReady(ionItem, () => resolve());
    });

    // Pierce Shadow DOM and set role/aria-label directly on the native button
    // This is needed for VoiceOver compatibility in Safari mobile
    const nativeButton = ionItem.shadowRoot?.querySelector('button');
    if (nativeButton) {
      nativeButton.setAttribute('role', menuItemRole);
    }
  }

```

File: libs/designsystem/menu/src/menu.component.ts [hunk 1]
```diff
@@ -294,18 +295,36 @@ export class MenuComponent implements AfterViewInit, AfterContentInit, OnDestroy
...
+      if (nativeInput) {
+        this.renderer.setAttribute(nativeInput, 'role', 'menuitemcheckbox');
+        return;
+      }
+    } else {
+      const nativeButton = ionItem.shadowRoot?.querySelector('button');
+      if (nativeButton) {
+        this.renderer.setAttribute(nativeButton, 'role', 'menuitem');
+      }
     }
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/menu/src/menu.component.ts]: Consider replacing this badboy with something a little more readable 👀  
```suggestion
     const ionItem = item.querySelector<HTMLIonItemElement>('ion-item');
    if (!ionItem) return;

    await new Promise<void>((resolve) => componentOnReady(ionItem, resolve));

    const checkableInput = ionItem
      .querySelector('ion-toggle, ion-checkbox')
      ?.shadowRoot?.querySelector('input');
    const button = ionItem.shadowRoot?.querySelector('button');
    const nativeControl = checkableInput ?? button;

    if (!nativeControl) return;
    this.renderer.setAttribute(
      nativeControl,
      'role',
      checkableInput ? 'menuitemcheckbox' : 'menuitem'
    );
```

**Review by RasmusKjeldgaard — COMMENTED** [review]
One small suggestion for a refactor, otherwise its looking good!

**Review by RasmusKjeldgaard — APPROVED** [review]
