### PR TITLE
Tab Navigation: Set selected and focussed tabs on changes

### LINKED ISSUE #3420: kirby-tab-navigation issue when adding/removing kirby-tab-navigation-item dynamicly
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Using async pipe to add/remove kirby-tab-navigation-item dynamicly will result in a selectedIndex with wrong value - trying to set i manually doesn't seam to work well. 

Visually something goes wrong when applying *ngIf="someValue | async" to kirby-tab-navigation-item and you scroll the page!

## Which Kirby version was used?
"@kirbydesign/designsystem": "^9.3.2",

## Add any screenshots
image_720

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
This PR closes #3420 

## What is the new behavior?
If slotted tab-navigation-items change, we update selected and focussed tabs accordingly. 
This allows users to set new values for selectedIndex and focusIndex when adding or removing items, so the template and logic stays in sync. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

**Review by jkaltoft — DISMISSED** [review]
Proforma approved (test a workflow)

File: libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts [hunk 1]
```diff
@@ -142,4 +134,29 @@ export class TabNavigationComponent implements AfterViewInit {
...
+    this.tabElements.forEach((tabElement) =>
+      this.tabButtonElements.push(tabElement.querySelector('[role="tab"]'))
+    );
+
+    this.selectTab(this.selectedIndex);
+    this.focusTab(this.focusIndex);
+
+    setTimeout(() => {
+      this.scrollToTab(this.focusIndex);
+    }, this.DEBOUNCE_TIME_MS);
```
Comment (jakobe) [inline libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts:152]: Seems this has both been moved _and_ refactored (`selectTab` and `focusTab` called outside timeout) — are we sure this doesn't cause any regressions? 🤔

Comment (RasmusKjeldgaard) [reply libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.ts:152]: The refactoring is intentional, otherwise there will be a visible delay when removing or inserting tab-items, as selection and focus happens asynchronously: 
https://github.com/kirbydesign/designsystem/assets/42470636/259c1807-f46e-49a8-b90a-4f4c9fc98867

Both `selectTab` and `focusTab` are all about manipulating the slotted html elements, and they are either called in AfterViewInit or when changes to a ContentChild is observed, so they should be safe to run at that point without delay.

**Review by jakobe — APPROVED** [review]
