### PR TITLE
Input & Textarea: emit kirbyChange on form value change

### LINKED ISSUE #3793: [BUG] Input counter not fully working with ReactiveForms
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When creating a Reactive Form in combination with a `kirby-form-field` having an `input[kirby-input]` as well as `kirby-input-counter`, things work quite well with user interactions. This includes manually entering text, copy pasting values etc - then counter updates as expected (which is great).

However, when the `FormControl` (bound from the Reactive Form) is programmatically updated, the input counter is not updated!

Template:

```html
<kirby-form-field>
  <input kirby-input [formControl]="name" [size]="size" placeholder="Enter your name (max 20 chars)" #name maxlength="20" />
  <kirby-input-counter [listenTo]="name"></kirby-input-counter>
</kirby-form-field>
<button kirby-button (click)="save()">Save</button>
```

Component (snippet):
```ts
// ...

protected name = new FormControl('')

protected save() {
  // ... Persist name by calling backend, then clear the field
  this.name.setValue('');
}

//...
```

## Describe how to reproduce the bug

There's no simple way to reproduce the bug in the cookbook, but I've provided a "minimal reproduce"-scenario in the "Describe the bug"-section of this bug report

## Which Kirby version was used?
10.1.3

## What was the expected behavior?
The counter is updated, regardless

## Please complete the following information:
- OS: Windows 11
- Browser: Edge, Chrome, Firefox (all)
- Browser version: latest

## Are there any additional context?

Having looked into the implementation of the `InputCounterComponent` (and `InputComponent`) it seems like the problem occurs due to the `InputComponent` only emitting `kirbyChange`-events on [Element: keyup event](https://developer.mozilla.org/en-US/docs/Web/API/Element/keyup_event). 

This is however not triggered upon imperative interactions with the `FormControl` API.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by lydemann**
## Which issue does this PR close?

This PR closes #3793 

## What is the new behavior?

Make counter update with reactive forms

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/form-field/src/textarea/textarea.component.ts [hunk 1]
```diff
@@ -67,6 +76,28 @@ export class TextareaComponent implements OnChanges, FormFieldControl {
...
+  }
+
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  registerOnTouched(_fn: any): void {
+    // handled in textarea Angular component
+  }
+
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  setDisabledState?(_isDisabled: boolean): void {
+    // handled in textarea Angular component
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/form-field/src/textarea/textarea.component.ts:98]:
```suggestion
    // handled textarea Angular component
```

File: libs/designsystem/form-field/src/textarea/textarea.component.ts [hunk 2]
```diff
@@ -67,6 +76,28 @@ export class TextareaComponent implements OnChanges, FormFieldControl {
...
+  writeValue(value: string): void {
+    if (value !== this.value) {
+      this.kirbyChange.emit(value);
+      this.value = value;
+    }
+  }
+
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  registerOnChange(_fn: any): void {
+    // handled in textarea Angular component
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/textarea/textarea.component.ts]:
```suggestion
    // handled by built-in textarea support in Angular 
```

File: libs/designsystem/form-field/src/textarea/textarea.component.ts [hunk 3]
```diff
@@ -67,6 +76,28 @@ export class TextareaComponent implements OnChanges, FormFieldControl {
...
+  }
+
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  registerOnTouched(_fn: any): void {
+    // handled in textarea Angular component
```
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/textarea/textarea.component.ts]:
```suggestion
    // handled by built-in textarea support in Angular 
```

File: libs/designsystem/form-field/src/textarea/textarea.component.ts (hunk 1 above)
Comment (Fuzzy3) [inline libs/designsystem/form-field/src/textarea/textarea.component.ts]:
```suggestion
    // handled by built-in textarea support in Angular 
```

**Review by RasmusKjeldgaard — APPROVED** [review]
