### PR TITLE
Mute "ResizeObserver loop limit exceeded" exception

### LINKED ISSUE #2031: [BUG] Exception: ResizeObserver loop limit exceeded
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
As part of reducing errors in general we discovered **Exception: ResizeObserver loop limit exceeded** in Azure App Insights. 
The exception is thrown when a page implements kirby-page with fit directive. The bug only occur in Chrome Webview. 

## Describe how to reproduce the bug
1. Execute any application that implements kirby-page with fit-directive in any way on the Android Emulator
2. navigate to the view/page
3. See the exception thrown in Logcat.

## Which Kirby version was used?
5.0.18 (The bug has been known for some time but was only now located as a bug within kirby-page)

## What was the expected behavior?
The bug has apparently no implications for the user.

## Please complete the following information:
- OS: Android
- Browser: Chrome Webview
- Browser version: 87, 94, 96, 97, 98 (according to Azure App Insights - probably more)

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by troelslenda**
## Which issue does this PR close?

This PR closes #2031

## What is the new behavior?

No ResizeObserver exceptions thrown in Azure App Insight when navigating to select pages
```
/drb/investment/securities
/drb/investment/overview
/drb/inbox
```
Other routes should be thoroughly tested.

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

It's unclear if the changes has any sideeffects. It should be tested.

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [ ] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

### CODE REVIEW

File: libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts [hunk 1]
```diff
@@ -73,9 +73,14 @@ export class FitHeadingDirective implements OnInit, OnDestroy {
...
-      this.scaleHeader();
-    });
+    // Supress errors thrown from ResizeObserver as they do not have any impact
+    // on the users.
+    // @see {@link https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded}
+    try {
+      this.resizeObserverService.observe(this.elementRef, () => {
+        this.scaleHeader();
+      });
+    } catch (e) {}
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts:83]: Nice! 

I think we should check the message field of the error as to not unintentionally mute other errors. 

The standard error message is "_ResizeObserver loop completed with undelivered notifications._" according to [the spec](https://www.w3.org/TR/resize-observer/#deliver-resize-error). According to [this guy](https://github.com/maslianok/react-resize-detector/issues/45#issuecomment-858810843) Chromium based browser might have another message set tho for some reason.

Which i believe is the one you might be seeing when testing from an Android based phone. 

So we might have to check both. 

So something like the below i guess 🤷 

```typescript 
catch(e) {
   if message is either chrome message or standard message: 
      do nothing 
   else: 
      throw(e); 
}

Comment (MadsBuchmann) [reply libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts:83]: Also if this turns out to give problems or not work - let's revert to the requestAnimationFrame solution. But i think this one might be the least intrusive solution for now.

File: libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts [hunk 2]
```diff
@@ -73,9 +73,18 @@ export class FitHeadingDirective implements OnInit, OnDestroy {
...
-    });
+    // Supress select errors thrown from ResizeObserver as they do not have any
+    // impact on the users.
+    // @see {@link https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded}
+    try {
+      this.resizeObserverService.observe(this.elementRef, () => {
+        this.scaleHeader();
+      });
+    } catch (e) {
+      if (e !== 'ResizeObserver loop limit exceeded') {
```
Comment (jkaltoft) [inline libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts:84]: Is there a "safer" way to not catch this particular error than using string comparison?

File: libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts (hunk 1 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/src/lib/directives/fit-heading/fit-heading.directive.ts]: Reverted to the requestAnimationFrame due to time constraints. 
The new proposed solution did not catch the error, and we need to investigate the error object a bit more to find out how to filter it. Unfortunately the process is slow, as we have to build kirby, install it in a project, and run the emulator to get feedback, so we will have to investigate more at a later time.

**Review by jkaltoft — APPROVED** [review]
