### PR TITLE
Progress circle: fix wrong animation direction

### LINKED ISSUE #3441: [BUG] Progress Circle load animation is wrong direction
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When the progress circle is visible on page load, the animation goes from 100% progress backwards towards the value set by consumers, instead of building up from 0 towards the set value.

This does not happen when the progress circle is below the fold, and the animation is triggered by the intersection observer once the progress circle is scrolled into view. 

## Describe how to reproduce the bug
1. Go to https://cookbook.kirby.design/#/home/showcase/progress-circle 
2. See that the progress circles immediately visible loads counter-clockwise from full to value
3. Scroll down to see progress circles previously hidden outside the viewport animating correctly, clockwise from 0 to value

## Which Kirby version was used?
9.4.1

## What was the expected behavior?
Progress circle should animate clockwise from 0 to the set value on page load and when scrolled into view.

## Are there any additional context?
Here are the offset and centerCircumference values when it loads the wrong way around
image

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?
This PR closes #3441

## What is the new behavior?
The issue described here https://github.com/kirbydesign/designsystem/issues/3441#issuecomment-2056620529 happens because the colored part of the circle is rendered before the attribute bindings for `stroke-dashoffset` and `stroke-dasharray` have been evaluated, so the full circle is shown.

A view-initialized class is now added when the components view is rendered, and we then wait until this class is added before we apply the transition.

Additionally, instead of using stroke-dashoffset I have refactored the stroke to use only the dasharray attribute to set a stroke and gap length. 
One downside of this approach is that even with a stroke of length 0, we end up applying a stroke width, so we always draw a little dot when the value is 0. 
image
To work around this I have added a conditional that sets the stroke width to 0, when value is 0.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/progress-circle/src/progress-circle-ring.component.ts [hunk 1]
```diff
@@ -39,7 +30,18 @@ export class ProgressCircleRingComponent {
...
+
+    return (_value * this._centerCircumference) / 100;
+  }
+
+  get _remainder(): number {
+    return this._centerCircumference - this._progress;
+  }
+
+  get _progressStrokeWidth(): number {
+    return this.value == 0 ? 0 : this.strokeWidth;
```
Comment (jakobe) [inline libs/designsystem/progress-circle/src/progress-circle-ring.component.ts]: Maybe add a comment as to why this is necessary - and/or implement with a guard to make the intent clearer:
```suggestion
    // Don't render stroke if value is 0, otherwise it will show as a dot:
    if (this.value === 0) return 0;
    return this.strokeWidth;
```

File: libs/designsystem/progress-circle/src/progress-circle-ring.component.ts [hunk 2]
```diff
@@ -39,7 +30,18 @@ export class ProgressCircleRingComponent {
     return this._centerRadius * 2 * Math.PI;
   }
 
-  private calculateOffset(value: number): number {
-    return this._centerCircumference - this._centerCircumference * (value / 100);
+  get _progress(): number {
+    const valueWithinBounds = this.value < this.upperBound || this.value > 99;
+    const _value = valueWithinBounds ? this.value : this.upperBound;
+
+    return (_value * this._centerCircumference) / 100;
```
Comment (jakobe) [inline libs/designsystem/progress-circle/src/progress-circle-ring.component.ts]: Consider readability, ie. as in the original `calculateOffset` method - the progress is a percentage (value out of 100) times the circumference 
```suggestion
    return this._centerCircumference * (_value / 100);
```
OR even more explicit:
```suggestion
    const progressPercentage = _value / 100;
    return this._centerCircumference * progressPercentage;
```

File: libs/designsystem/progress-circle/src/progress-circle-ring.component.scss [hunk 3]
```diff
@@ -9,13 +9,18 @@ svg {
...
   transition-timing-function: utils.get-transition-easing('enter-exit');
   transform-origin: 50% 50%;
   stroke: var(--kirby-progress-circle-stroke-color, #{utils.get-color('success')});
 }
 
+// Avoid flash of full progress circle if attribute binding in template has not yet been evaluated.
+.progress:not([stroke-dasharray]) {
+  stroke-dasharray: 0 999;
+}
+
```
Comment (jakobe) [inline libs/designsystem/progress-circle/src/progress-circle-ring.component.scss]: Consider grouping with rest of `.progress` styles:
```suggestion
  stroke: var(--kirby-progress-circle-stroke-color, #{utils.get-color('success')});
  // Avoid flash of full progress circle if attribute binding in template has not yet been evaluated.
  &:not([stroke-dasharray]) {
    stroke-dasharray: 0 999;
  }
}
```

**Review by jakobe — COMMENTED** [review]
Looks really grreat! Just a few suggestions for minor improvements, mainly around redability 👌🏻

**Review by jakobe — DISMISSED** [review]

**Review by jakobe — APPROVED** [review]
