### PR TITLE
Page: make 'standard' the default maxWidth option

### LINKED ISSUE #2975: [BUG] Remove deprecated "Standard" Page maxWidth
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
 

The default max width for all pages, that don't use the "optimized" or "full" should be 792px instead of 720px. It is not something the teams should set.

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by thupi**
## Which issue does this PR close?

This PR closes #2975 

## What is the new behavior?

Kirby Page has a property called maxWidth. This changes the default to have the same value as 'standard' and then deprecates the 'standard' option.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/page/src/page.component.ts [hunk 1]
```diff
@@ -210,7 +210,7 @@ export class PageComponent
   @Input() defaultBackHref: string;
   @Input() hideBackButton: boolean;
   @Input() titleMaxLines: number;
-  @Input() maxWidth: 'default' | 'standard' | 'optimized' | 'full' = 'default';
+  @Input() maxWidth: 'default' | 'optimized' | 'full' = 'default';
```
Comment (thupi) [inline libs/designsystem/page/src/page.component.ts]: Apply this to prevent breaking changes as the API will stay the same. However, the option will be redundant with default as those will result in the samme thing. 

```suggestion
  @Input() maxWidth: 'default' | 'standard' | 'optimized' | 'full' = 'default';
```

Comment (RasmusKjeldgaard) [reply libs/designsystem/page/src/page.component.ts]: I think it is better to prevent the breaking change and `console.log()` a deprecation warning whenever `standard` is used. And then remove `standard` in v10.

**Comment by mark-drastrup** [comment]
NOTE: This PR should NOT be merged before #3003 is merged.

File: libs/designsystem/page/src/page.component.scss [hunk 2]
```diff
@@ -267,10 +267,6 @@ ion-content {
     --padding-top: 0;
   }
 
-  &.max-width-standard {
-    --page-content-max-width: 792px;
-  }
-
   &.max-width-optimized {
     --page-content-max-width: 1092px;
```
Comment (jakobe) [inline libs/designsystem/page/src/page.component.scss]: Magic number? 🪄

File: libs/core/src/scss/base/_variables.scss [hunk 3]
```diff
@@ -126,7 +126,7 @@ $avatar-badge-size: 16px;
 
 /* Page
 ****************************************************************************/
-$page-content-max-width: 720px;
+$page-content-max-width: 792px;
```
Comment (jakobe) [inline libs/core/src/scss/base/_variables.scss]: Consider naming:
```suggestion
$page-content-default-max-width: 792px;
```

File: libs/designsystem/page/src/page.component.spec.ts [hunk 4]
```diff
@@ -793,7 +793,7 @@ describe('PageComponent', () => {
         await TestHelper.whenReady(ionContent);
         const contentInner = ionContent.querySelector('.content-inner');
         expect(contentInner).toHaveComputedStyle({
-          'max-width': '720px',
+          'max-width': DesignTokenHelper.pageContentMaxWidth('default'),
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/page/src/page.component.spec.ts:796]: Used DesignTokenHelper here instead of hardcoded values as I think the unit under test is the page and its consistency/alignment with tokens, not the actual value.

File: MIGRATION.md [hunk 5]
```diff
@@ -28,6 +28,16 @@ The Experimental Alert has been fully removed and we recommend to use the normal
...
 A new `xsmall` breakpoint (`320px`) has been introduced in the `$breakpoints` map exposed by Kirby. The `xsmall` breakpoint replaces the old `small` breakpoint, which is now `632px`.
 
+A `$page-content-max-widths` map has been introduced to support `default`, `optimized` and `full`-width content on Kirby Page, which means the standalone variable `$page-content-max-width` is now obsolete.
+For backwards compatability the `$page-content-max-width` scss variable returns the `default` value of the new map, but from the next major (v10) it will be removed and should be retreived directly from the map:
+
+```
+@use 'sass:map';
+@use '@kirbydesign/designsystem/scss/utils';
+
+map.get(utils.$page-content-max-widths, 'default')
```
Comment (jakobe) [inline MIGRATION.md]: Consider introducing a utility function as we do for font-size, line-height, font-weight etc...

File: libs/core/src/scss/base/_variables.scss [hunk 6]
```diff
@@ -119,7 +119,12 @@ $avatar-badge-size: 16px;
 
 /* Page
 ****************************************************************************/
-$page-content-max-width: 720px;
+$page-content-max-widths: (
+  default: 792px,
+  optimized: 1092px,
+  full: 100%,
+);
+$page-content-max-width: map.get($page-content-max-widths, 'default');
```
Comment (jakobe) [inline libs/core/src/scss/base/_variables.scss]: Consider adding a new variable for simpler usage, one that doesn't get deprecated/removed later:
```suggestion
$page-content-max-width: map.get($page-content-max-widths, 'default');
$page-content-max-width-default: map.get($page-content-max-widths, 'default');
```

File: libs/designsystem/page/src/page-footer/page-footer.component.scss [hunk 7]
```diff
@@ -11,7 +12,7 @@ $padding-vertical: utils.size('xxs');
 
   .wrapper {
     position: relative;
-    max-width: var(--page-content-max-width, utils.$page-content-max-width);
+    max-width: var(--page-content-max-width, #{map.get(utils.$page-content-max-widths, 'default')});
```
Comment (jakobe) [inline libs/designsystem/page/src/page-footer/page-footer.component.scss]: Consider using variable for readability and simpler usage:
```suggestion
    max-width: var(--page-content-max-width, $page-content-max-width-default);
```

**Review by jakobe — CHANGES_REQUESTED** [review]

File: libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss [hunk 8]
```diff
@@ -1,8 +1,9 @@
+@use 'sass:map';
```
Comment (jakobe) [inline libs/designsystem/tab-navigation/src/tab-navigation/tab-navigation.component.scss]: I believe this is obsolete now? 🔥 
```suggestion
```

File: libs/designsystem/page/src/page-footer/page-footer.component.scss [hunk 9]
```diff
@@ -1,3 +1,4 @@
+@use 'sass:map';
```
Comment (jakobe) [inline libs/designsystem/page/src/page-footer/page-footer.component.scss]: I believe this is obsolete now? 🔥 
```suggestion
```

File: libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss [hunk 10]
```diff
@@ -1,10 +1,11 @@
+@use 'sass:map';
```
Comment (jakobe) [inline libs/designsystem/src/lib/components/page-local-navigation/page-local-navigation.component.scss]: I believe this is obsolete now? 🔥 
```suggestion
```

**Review by jakobe — CHANGES_REQUESTED** [review]

**Review by jakobe — APPROVED** [review]
giphub
