### PR TITLE
Button: Reworked eventlistener to effectively block event bubbling when button is aria-disabled

### LINKED ISSUE #3807: [BUG] NVDA will trigger click-event on a aria-disabled button wrapped inside kirby-app
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
NVDA will trigger click-event on a aria-disabled button wrapped inside kirby-app

## Which Kirby version was used?
10.3.0

## What was the expected behavior?
no click event happening

## Add any screenshots
https://stackblitz.com/edit/stackblitz-starters-crsnt4nz?file=src%2Fmain.ts

## Please complete the following information:
- OS: Windows 11
- Browser Chrome: 133.0.6943.127, Edge: 132.0.2957.171 

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Fuzzy3**
## Which issue does this PR close?

This PR closes #3807 

## What is the new behavior?
It is not possible to block events when using the angular hostlistener on click and keydown events (see https://github.com/angular/angular/issues/9587), thus the blocking of event-bubbling when the button is aria-disabled, is now handled by registering eventlisteners using the renderer of angular. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed]~~ (https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/button/src/button.component.ts [hunk 1]
```diff
@@ -92,10 +93,28 @@ export class ButtonComponent implements AfterContentInit {
   @ContentChild(IconComponent, { read: ElementRef })
   iconElementRef?: ElementRef<HTMLElement>;
 
+  private removeListeners: (() => void)[] = [];
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/button/src/button.component.ts]: Name might be slightly confusing, consider renaming and leaving the "removal" stuff as an implementation detail in ngOnDestroy. 

```suggestion
  private eventListeners: (() => void)[] = [];
```

File: libs/designsystem/button/src/button.component.ts [hunk 2]
```diff
@@ -153,9 +172,10 @@ export class ButtonComponent implements AfterContentInit {
     }
   }
 
-  @HostListener('keydown.enter', ['$event'])
-  @HostListener('keydown.space', ['$event'])
-  _onEnterOrSpace(event: KeyboardEvent) {
+  ngOnDestroy() {
+    this.removeListeners.forEach((removeListener) => removeListener());
+  }
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/button/src/button.component.ts]: Consider placing ngOnDestroy as last method

**Review by RasmusKjeldgaard — COMMENTED** [review]
Nice! 👏

File: libs/designsystem/button/src/button.component.ts [hunk 3]
```diff
@@ -92,10 +92,28 @@ export class ButtonComponent implements AfterContentInit {
   @ContentChild(IconComponent, { read: ElementRef })
   iconElementRef?: ElementRef<HTMLElement>;
 
+  private removeEventListeners: (() => void)[] = [];
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/button/src/button.component.ts]: Consider reusing the existing `EventListenerDisposeFn` for this, and match the pattern used in e.g. dropdown.

File: libs/designsystem/button/src/button.component.ts [hunk 4]
```diff
@@ -92,10 +93,28 @@ export class ButtonComponent implements AfterContentInit {
...
   iconElementRef?: ElementRef<HTMLElement>;
 
+  private disposeEvents: EventListenerDisposeFn[] = [];
+
   constructor(
     private elementRef: ElementRef<HTMLElement>,
     private renderer: Renderer2
-  ) {}
+  ) {
+    this.setupEventListenerForAriaDisabledHandling();
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/button/src/button.component.ts:105]: Consider moving to ngOnInit to do as little work in constructor as possible.

File: libs/designsystem/dropdown/src/dropdown.component.ts [hunk 5]
```diff
@@ -250,7 +250,7 @@ export class DropdownComponent implements AfterViewInit, OnDestroy, ControlValue
     return this._kirbyItemsSlotted;
   }
 
-  private itemClickUnlisten: EventListenerDisposeFn[] = [];
+  private disposeItemClicks: EventListenerDisposeFn[] = [];
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/dropdown/src/dropdown.component.ts]: I'd prefer this naming for clarity throughout the files. Thoughts?
```suggestion
  private disposeItemClickListeners: EventListenerDisposeFn[] = [];
```

Comment (Fuzzy3) [reply libs/designsystem/dropdown/src/dropdown.component.ts]: I like that! Its the listener that is disposed and not the event itself

**Review by RasmusKjeldgaard — DISMISSED** [review]
👏

**Review by RasmusKjeldgaard — APPROVED** [review]
