### PR TITLE
Reference BadgeComponent directly in lib index.ts to mitigate UMD compilation bug

### LINKED ISSUE #1740: [BUG] UMD Compilation issue for npm package
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When installing the Kirby Package in consumer projects via npm, the UMD compilation step where the angular compatibility compiler (ngcc) tries to compile the Kirby UMD bundle will cause a `RangeError: Maximum call stack size exceeded`.

## Describe how to reproduce the bug

1. `npm run publish` in Kirby Design on branch enhancement/web-components/
2. Install .tgz file from designsystem/dist folder
3. Run `npx ngcc --properties main` to compile UMD bundles
4. See error when we get to 'Compiling @kirbydesign/designsystem' (or at some later point during the process - the compilation runs asynchronously, so it might look like it happens during other compilation steps, even though Kirby is at fault)

## Which Kirby version was used?
3.0.9

## What was the expected behavior?
No compilation error!

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](../SUPPORT.md/#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
~~- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test]~~(https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [x] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [x] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #1740 

## What is the new behavior?
Moved the Badge type export one level up, as the current nested structure that referenced badge through a /components/ barrel file resulted in a UMD compilation error in consumer projects ('RangeError: Maximum call stack size exceeded'). 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](../CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
~~- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".~~
~~- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).~~

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
~~- [ ] Request that the changes are [UX reviewed](./CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

### CODE REVIEW

File: libs/designsystem/src/lib/index.ts [hunk 1]
```diff
@@ -5,4 +5,6 @@ export * from './helpers';
 export * from './scss/scss-helper';
 // export * from './testing';
 
+export { KirbyBadge as BadgeComponent } from './components/web-component-proxies.component';
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/index.ts:8]: Perhaps add a comment stating that everything will go wrong and Cthulhu will be summoned if badge is not exported this way.

**Review by MadsBuchmann — APPROVED** [review]
Fine as a temporary solution for me such that we can move forwards. I will still do a bit of digging with the stuff I'm playing around with as part of this bug. 

The _temporary_ part is that we should perhaps find a way to expose webComponents that scales a bit better, instead of cluttering the lib/index.ts file. 

But might be troublesome with the umd bug'n'all.

File: libs/designsystem/src/lib/index.ts (hunk 1 above)
Comment (RasmusKjeldgaard) [reply libs/designsystem/src/lib/index.ts:11]: Fixed in 99f0a74

**Review by jkaltoft — APPROVED** [review]
