### PR TITLE
Make custom icon name usable in Segmented Control badge

### LINKED ISSUE #1890: [BUG] Custom icon is not loaded in SegmentedControl
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If an item in the SegmentedControl has the 'badge.icon' field, it is used as both the customName for the icon in the template. This means that the icon will first try to use the custom icons name for the 'name' input (default icons), before applying the custom icon name to the 'customName' input of the icon. When no 'name' matches the custom name that has been inputted, the default icon is used, before we ever try to search through the custom icons registry.

## Describe how to reproduce the bug
Change the Segmented Badge with Badge cookbook page to use a custom icon (umbrella or football), and the cog icon appearing instead. 

## Which Kirby version was used?
4.0.13

## What was the expected behavior?
Both customIcons and icons should work. 

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/master/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [master branch](https://github.com/kirbydesign/designsystem/tree/master) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #1890
## What is the new behavior?
It is now possible to specify an icon with a custom name for the Segmented Control badge. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/master/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be automatically merged to master via [automerge](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request).

### CODE REVIEW

File: libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts [hunk 1]
```diff
@@ -35,13 +39,23 @@ export class SegmentedControlComponent {
...
   @Input() set items(value: SegmentItem[]) {
     this._items = value || [];
+    this._items.forEach((item) => {
+      // We need to verify whether badges icon is custom or default, so we can check for it in the template
+      if (
+        item.badge?.icon !== undefined &&
+        this.iconRegistryService.getIcon(item.badge.icon) !== undefined
+      ) {
+        item.badge.isCustomIcon = true;
+      }
```
Comment (MadsBuchmann) [inline libs/designsystem/src/lib/components/segmented-control/segmented-control.component.ts:56]:
```suggestion
        item.badge.isCustomIcon =  item.badge?.icon !== undefined &&
        this.iconRegistryService.getIcon(item.badge.icon) !== undefined;
```

**Review by MadsBuchmann — APPROVED** [review]
Dog LGTM

**Review by MadsBuchmann — APPROVED** [review]
