### PR TITLE
List: allow adding accessible name to list element

### LINKED ISSUE #3956: [BUG] missing aria-label for list
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When we're trying to add a [attr.aria-label] or aria-label to a 'kirby-list' this will add the label to a group surrounding the list. We have tried with VO. 

But if we add role="list" to the kirby-list and role="listitem" to the underlying child kirby-items. Then the name appears on the kirby-list. But there also appears an extra list inside the kirby-list without an accessible name when we check it with VO. 

## Describe how to reproduce the bug

Try creating a kirby-list and adding an aria-label. 

Then try testing it with a screenreader fx VoiceOver. 

```
<kirby-list [items]="infoLinks" aria-label="Liste med links">
    <kirby-item *kirbyListItemTemplate="let item"> {{ item.text }} </kirby-item>
</kirby-list>
```
## Which Kirby version was used?
10.3.0

## What was the expected behavior?
The expected behavior is that the list has an accessible name. 

## Add any screenshots
No screenshots provided. 

## Please complete the following information:
- OS: MacOs
- Browser: Chrome (Version 136.0.7103.114)
- Browser: Safari (Version 18.3.1 (20620.2.4.11.6))

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by Loujuu**
## Which issue does this PR close?

This PR closes #3956

## What is the new behavior?

aria-label and aria-labelledby added to list component

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: apps/cookbook/src/app/examples/list-example/examples/items.ts [hunk 1]
```diff
@@ -5,12 +5,12 @@ import { ListModule } from '@kirbydesign/designsystem/list';
 import { ItemModule } from '@kirbydesign/designsystem/item';
 import { BaseListComponent } from '../../list-shared/base-list.component';
 
-export const ListItemsExampleTemplate = `<kirby-list [items]="items">
+export const ListItemsExampleTemplate = `<kirby-list [items]="items" aria-label="Campanies">
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/examples/list-example/examples/items.ts]:
```suggestion
export const ListItemsExampleTemplate = `<kirby-list [items]="items" aria-label="Companies">
```

File: apps/cookbook/src/app/showcase/list-load-on-demand-showcase/list-load-on-demand-showcase.component.html [hunk 2]
```diff
@@ -35,6 +35,21 @@
...
+  <code>aria-label</code>
+  or
+  <code>aria-labelledby</code>
+  attribute on the
+  <code>kirby-list</code>
+  .
+  <br />
+  More information can be found in the
+  <a href="https://cookbook.kirby.design/#/home/showcase/list">List.</a>
+  .
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/list-load-on-demand-showcase/list-load-on-demand-showcase.component.html]:
```suggestion
  More information can be found in 
  <a href="/home/showcase/list">the list showcase.</a>
```

File: apps/cookbook/src/app/showcase/list-no-shape-showcase/list-no-shape-showcase.component.html [hunk 3]
```diff
@@ -45,3 +45,18 @@ <h2>List item wrapped in card</h2>
...
+  <code>aria-label</code>
+  or
+  <code>aria-labelledby</code>
+  attribute on the
+  <code>kirby-list</code>
+  .
+  <br />
+  More information can be found in the
+  <a href="https://cookbook.kirby.design/#/home/showcase/list">List.</a>
+  .
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/list-no-shape-showcase/list-no-shape-showcase.component.html]:
```suggestion
  More information can be found in 
  <a href="/home/showcase/list">the list showcase.</a>
```

File: apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html [hunk 4]
```diff
@@ -152,6 +152,28 @@ <h2>List with sections and standalone items:</h2>
...
+</p>
+<p>
+  The
+  <code>kirby-list</code>
+  component uses correct ARIA roles (
+  <code>role="list"</code>
+  and
+  <code>role="listitem"</code>
+  on its children) to ensure that assistive technologies recognize the structure as a list. The
+  accessible label you provide will be announced together with the number of items in the list.
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html]: I like this description, but i'm unsure if we need it the description of something we do internally. We could remove most of it and maybe just leave the last sentence: "The accessible label you provide will be announced together with the number of items in the list."

File: apps/cookbook/src/app/showcase/list-swipe-showcase/list-swipe-showcase.component.html [hunk 5]
```diff
@@ -2,3 +2,19 @@
...
+  <code>aria-label</code>
+  or
+  <code>aria-labelledby</code>
+  attribute on the
+  <code>kirby-list</code>
+  .
+  <br />
+  More information can be found in the
+  <a href="https://cookbook.kirby.design/#/home/showcase/list">List.</a>
+  .
```
Comment (Fuzzy3) [inline apps/cookbook/src/app/showcase/list-swipe-showcase/list-swipe-showcase.component.html]:
```suggestion
  More information can be found in 
  <a href="/home/showcase/list">the list showcase.</a>
```

File: libs/designsystem/list/src/list.component.spec.ts [hunk 6]
```diff
@@ -220,4 +220,22 @@ describe('ListComponent', () => {
       });
     });
   });
+
+  describe('aria attributes', () => {
+    it('should forward aria-label to ion-list', () => {
+      spectator.setInput({ items: transactions });
```
Comment (Fuzzy3) [inline libs/designsystem/list/src/list.component.spec.ts]: Do we need this?

File: libs/designsystem/list/src/list.component.spec.ts [hunk 7]
```diff
@@ -220,4 +220,22 @@ describe('ListComponent', () => {
...
+      spectator.element.setAttribute('aria-label', 'My Accessible List');
+      component.ngAfterViewInit();
+      const list = spectator.query('ion-list');
+      expect(list.getAttribute('aria-label')).toBe('My Accessible List');
+    });
+
+    it('should forward aria-labelledby to ion-list', () => {
+      spectator.setInput({ items: transactions });
```
Comment (Fuzzy3) [inline libs/designsystem/list/src/list.component.spec.ts]: Do we need this?

**Review by Fuzzy3 — DISMISSED** [review]
Good job ! I have few nitty grittys about the cookbook formulation. Other than that, it is great !

File: apps/cookbook/src/app/examples/list-example/examples/items.ts [hunk 8]
```diff
@@ -5,12 +5,12 @@ import { ListModule } from '@kirbydesign/designsystem/list';
 import { ItemModule } from '@kirbydesign/designsystem/item';
 import { BaseListComponent } from '../../list-shared/base-list.component';
 
-export const ListItemsExampleTemplate = `<kirby-list [items]="items">
+export const ListItemsExampleTemplate = `<kirby-list [items]="items" aria-label="Companies">
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/list-example/examples/items.ts]: I'm unsure if we should add the aria-label to this example. I think in most cases, a list will have the proper context based on a heading prior to the element, so the aria-label stuff should probably not be added to our primary example 🤔

File: apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html [hunk 9]
```diff
@@ -152,6 +152,21 @@ <h2>List with sections and standalone items:</h2>
   </div>
 </div>
 
+<h2>Accessibility</h2>
+<h3>Lists</h3>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html]: This heading is probably a bit redundant, since we are in a list showcase.
```suggestion
```

File: apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html [hunk 10]
```diff
@@ -152,6 +152,21 @@ <h2>List with sections and standalone items:</h2>
...
+<p>
+  Always provide an accessible label for your list using the
+  <code>aria-label</code>
+  or
+  <code>aria-labelledby</code>
+  attribute on the
+  <code>kirby-list</code>
+  component. This helps screen reader users understand the purpose and content of the list.
+</p>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html]: Are we sure consumers should always provide a label? 

My understanding (based on [this](https://www.scottohara.me/blog/2020/05/02/labelled-lists.html)) is that most of the time, the list will not need an explicit accessible name, but sometimes when multiple similar lists exist, it might be beneficial.

Unless you have other insights on this, I suggest to edit the paragraph to be about the possibility of adding a label here, but then not add the `aria-label` or `aria-labelledby` attribute to the code-examples, as we dont want it to be the main example.

File: libs/designsystem/list/src/list.component.spec.ts [hunk 11]
```diff
@@ -220,4 +220,20 @@ describe('ListComponent', () => {
       });
     });
   });
+
+  describe('aria attributes', () => {
+    it('should forward aria-label to ion-list', () => {
+      spectator.element.setAttribute('aria-label', 'My Accessible List');
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/list/src/list.component.spec.ts:226]: To make sure that it is acually forwarded, it would be good to add an expect that verifies that the label no longer exist on the original element.

**Review by RasmusKjeldgaard — COMMENTED** [review]
Good stuff! I think adding an accessible name to the list is somewhat of an edge-case (see https://www.scottohara.me/blog/2020/05/02/labelled-lists.html), and we should adjust the docs to reflect this, unless you have insight that point in another direction 😊 

Should this be categorized as a feature instead, since we add new functionality? If so, consider modifying the PR title to reflect that this is a new feature, e.g. "List: allow adding accessible name to list element", and change the label accordingly.

File: apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html (hunk 10 above)
Comment (Loujuu) [reply apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html]: I agree :-) You are right. I will change paragraph to possibility instead.

File: apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html [hunk 12]
```diff
@@ -152,6 +152,25 @@ <h2>List with sections and standalone items:</h2>
   </div>
 </div>
 
+<h2>Accessibility</h2>
+<p>
+  If the list has no apparent heading or in itself communicates a clear purpose, consider adding an
+  accesible name, to help screen reader users understand the purpose and content of the list.
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-showcase/list-showcase.component.html]:
```suggestion
  If the list has no apparent heading or does not in itself communicate a clear purpose, consider adding an
  accessible name to help screen reader users understand the purpose and content of the list.
```

File: apps/cookbook/src/app/showcase/list-no-shape-showcase/list-no-shape-showcase.component.html [hunk 13]
```diff
@@ -45,3 +45,17 @@ <h2>List item wrapped in card</h2>
     ></cookbook-multi-card-list-no-shape-example>
   </cookbook-example-viewer>
 </div>
+<h2>Accessibility</h2>
+<h3>Lists</h3>
+<p>
+  Always provide an accessible label for your list using the
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-no-shape-showcase/list-no-shape-showcase.component.html]: We should remove the list heading and update the text here too 😊

File: apps/cookbook/src/app/showcase/list-load-on-demand-showcase/list-load-on-demand-showcase.component.html [hunk 14]
```diff
@@ -35,6 +35,20 @@
   <cookbook-code-viewer [html]="exampleHtml"></cookbook-code-viewer>
   <cookbook-iphone src="/examples/list-load-on-demand" showExternalLink="true"></cookbook-iphone>
 </div>
+<h2>Accessibility</h2>
+<h3>Lists</h3>
+<p>
+  Always provide an accessible label for your list using the
+  <code>aria-label</code>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-load-on-demand-showcase/list-load-on-demand-showcase.component.html]: We should remove the list heading and update the text here too 😊

File: apps/cookbook/src/app/showcase/list-swipe-showcase/list-swipe-showcase.component.html [hunk 15]
```diff
@@ -2,3 +2,18 @@
   <cookbook-list-swipe-example></cookbook-list-swipe-example>
   <cookbook-code-viewer [html]="exampleHtml"></cookbook-code-viewer>
 </div>
+
+<h2>Accessibility</h2>
+<h3>Lists</h3>
+<p>
+  Always provide an accessible label for your list using the
+  <code>aria-label</code>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/list-swipe-showcase/list-swipe-showcase.component.html]: We should remove the list heading and update the text here too 😊

File: apps/cookbook/src/app/examples/list-example/examples/items.ts [hunk 16]
```diff
@@ -5,12 +5,12 @@ import { ListModule } from '@kirbydesign/designsystem/list';
 import { ItemModule } from '@kirbydesign/designsystem/item';
 import { BaseListComponent } from '../../list-shared/base-list.component';
 
-export const ListItemsExampleTemplate = `<kirby-list [items]="items">
+export const ListItemsExampleTemplate = `<kirby-list [items]="items" >
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/list-example/examples/items.ts]:
```suggestion
export const ListItemsExampleTemplate = `<kirby-list [items]="items">
```

**Review by RasmusKjeldgaard — APPROVED** [review]
