### PR TITLE
Range: Fix undefined pinFormatter on initialization

### LINKED ISSUE #3366: [BUG] Range with pin gives "pinFormatter is not a function" error
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
If the pin property of kirby-range is true, but no pinFormatter is supplied, a "pinFormatter is not a function" error occurs in some scenarios - for instance when showing the range in an outlet-based modal with multiple steps. Navigating away from a component with a range and back again will reproduce the bug. 

It does not happen when the range is loaded the first time around, so it seems like some re-initialization issue, where ion-range is maybe hydrated before the pinFormatter binding is evaluted, and thus receives `undefined` somehow at a later time?

## Describe how to reproduce the bug
The error can be provoked by explicitly setting the pinFormatter to undefined, and I assume something similar is happening in some cases during initialization of the component:
```
import { Component } from '@angular/core';

@Component({
  selector: 'cookbook-range-default-example',
  template: `
    <kirby-range [pin]="true" [pinFormatter]="pinFormatter"></kirby-range>
  `,
})
export class RangeDefaultExampleComponent {
  pinFormatter = () => {};

  constructor() {
    setTimeout(() => {
      this.pinFormatter = undefined;
    });
  }
}
```

## Which Kirby version was used?
9.2.1

## What was the expected behavior?
When pin is true but no pinFormatter is supplied the expected behavior is to just show the value in the pin.

## Add any screenshots
image

## Please complete the following information:
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

## Are there any additional context?

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [x] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/develop/.github/SUPPORT.md#team-kirby); do not proceed until this is done.

### Implementation 
The contributor who wants to implement this issue should: 

- [x] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#before-you-get-coding)".
- [x] Signal to others you are working on the issue by assigning yourself.
- [x] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by RasmusKjeldgaard**
## Which issue does this PR close?

This PR closes #3366

## What is the new behavior?
We always define a pinFormatter so we avoid initialization issues where the pinFormatter is undefined when forwarded to `ion-range`

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [ ] ~~Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/develop/.github/CONTRIBUTING.md#ux-review) (only necessary if your PR introduces visual changes)~~

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/range/src/range.component.ts [hunk 1]
```diff
@@ -99,6 +99,10 @@ export class RangeComponent implements OnChanges, OnInit, ControlValueAccessor {
     }
   }
 
+  private defaultPinFormatter(value: number): string | number {
+    return value;
+  }
```
Comment (jkaltoft) [inline libs/designsystem/range/src/range.component.ts]: Don't know if it's because my Typescript skill are rusty 😄, but this looks a bit odd to me.

How can `defaultPinFormatter()` return a string if it returns `value` and `value` is always a number?

Comment (RasmusKjeldgaard) [reply libs/designsystem/range/src/range.component.ts]: Fixed! I originally just matched the type signature of the pinFormatter but you are right it is not needed for the `defaultPinFormatter()` function

**Review by jkaltoft — COMMENTED** [review]
giphub

**Review by jkaltoft — APPROVED** [review]
