### PR TITLE
Checkbox: implement ControlValueAccessor to trigger changes within Angular forms

### LINKED ISSUE #2804: [BUG] kirby-checkbox does not trigger changes within reactive forms
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
I have attempted to add a kirby-checkbox to a reactive form. In the course of this I wrote a subscription to its value changes, like this:
`this.form.controls.checkboxDims.valueChanges.subscribe(value => console.log('checkbox value changed'));`

However this console statement is never triggered. As far as I can see, the value property of the control in the form is not updated, either.

According to @RasmusKjeldgaard , the kirby-checkbox does not implement the ControlValueAccessor interface.

This means that the kirby-checkbox can't currently be used within forms.

## Describe how to reproduce the bug
1. Create a component with a form, the form being defined like this: 
```

  form = new FormGroup({
    checkboxDims: new FormControl<Boolean | null>({ value: null, disabled: true }, Validators.required),
  });
```
2. Set up a dependency, for example in ngOnInit:
```
ngOnInit() {
  this.form.controls.checkboxDims.valueChanges.subscribe((value) => console.log(value));
}
```

## Which Kirby version was used?
8.0.0-rc.0

## What was the expected behavior?
That the console.log statement fired.

## Please complete the following information:
- OS: Windows
- Chrome
- 109.0.5414.75

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by AgreSanGit**
## Which issue does this PR close?

This PR closes #2804 

## What is the new behavior?

ControlValueAccessor implemented so kirby checkbox does now trigger changes within reactive forms

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [ ] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [ ] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 1]
```diff
@@ -51,9 +60,47 @@ export class CheckboxComponent {
...
     this.checkedChange.emit(this.checked);
+    this.onTouched();
   }
 
   // IDs used for a11y labelling
   _labelId = UniqueIdGenerator.scopedTo('kirby-checkbox-label').next();
+
+  //ControleValueAcessor
+  private onChange: (value: boolean) => void = () => {};
+  private onTouched: () => void = () => {};
```
Comment (mark-drastrup) [inline libs/designsystem/checkbox/src/checkbox.component.ts]:
```suggestion
  private _onTouched = () => {};
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 2]
```diff
@@ -51,9 +60,47 @@ export class CheckboxComponent {
...
+    this.onChange(this.checked);
     this.checkedChange.emit(this.checked);
+    this.onTouched();
   }
 
   // IDs used for a11y labelling
   _labelId = UniqueIdGenerator.scopedTo('kirby-checkbox-label').next();
+
+  //ControleValueAcessor
+  private onChange: (value: boolean) => void = () => {};
```
Comment (mark-drastrup) [inline libs/designsystem/checkbox/src/checkbox.component.ts]:
```suggestion
  private _onChange: (value: boolean) => void = () => {};
```

Comment (mark-drastrup) [reply libs/designsystem/checkbox/src/checkbox.component.ts]: This is just to follow the naming convention in other components, that also implements the ControlValueAccessor interface :)

File: libs/designsystem/checkbox/src/checkbox.component.ts (hunk 1 above)
Comment (mark-drastrup) [reply libs/designsystem/checkbox/src/checkbox.component.ts]: This is just to follow the naming convention in other components, that also implements the ControlValueAccessor interface :)

File: libs/designsystem/checkbox/src/checkbox.component.spec.ts [hunk 3]
```diff
@@ -202,4 +202,32 @@ describe('CheckboxComponent', () => {
       expect(spectator.component.checkedChange.emit).toHaveBeenCalledWith(false);
     });
   });
+  describe('ControlValueAccessor implementation', () => {
```
Comment (mark-drastrup) [inline libs/designsystem/checkbox/src/checkbox.component.spec.ts]:
```suggestion
  describe('implementing ControlValueAccessor interface', () => {
```

Comment (mark-drastrup) [reply libs/designsystem/checkbox/src/checkbox.component.spec.ts]: This is not important, but it's just the description that is being used in other test files, that tests for ControlCalueAccessor implementation :)

File: libs/designsystem/checkbox/src/checkbox.component.spec.ts [hunk 4]
```diff
@@ -202,4 +202,32 @@ describe('CheckboxComponent', () => {
...
+      spectator.component.writeValue(newValue);
+      expect(spectator.component.checked).toBe(newValue);
+    });
+
+    it('should call the registered onChange function when onChecked is called', () => {
+      const onChangeSpy = jasmine.createSpy('onChange');
+      const newValue = true;
+      spectator.component.registerOnChange(onChangeSpy);
+      spectator.component.onChecked(newValue);
+      expect(onChangeSpy).toHaveBeenCalledWith(newValue);
```
Comment (mark-drastrup) [inline libs/designsystem/checkbox/src/checkbox.component.spec.ts]:
```suggestion
      expect(onChangeSpy).toHaveBeenCalledOnceWith(newValue);
```

Comment (mark-drastrup) [reply libs/designsystem/checkbox/src/checkbox.component.spec.ts]: This is just to make sure that the onChange function is only called once :)

File: libs/designsystem/checkbox/src/checkbox.component.spec.ts [hunk 5]
```diff
@@ -202,4 +202,32 @@ describe('CheckboxComponent', () => {
...
+    });
+
+    it('should call the registered onTouched function when onChecked is called', () => {
+      const onTouchedSpy = jasmine.createSpy('onTouched');
+      spectator.component.registerOnTouched(onTouchedSpy);
+      spectator.component.onChecked(true);
+      expect(onTouchedSpy).toHaveBeenCalled();
```
Comment (mark-drastrup) [inline libs/designsystem/checkbox/src/checkbox.component.spec.ts]:
```suggestion
      expect(onTouchedSpy).toHaveBeenCalled(); 
      expect(onTouchedSpy).toHaveBeenCalledTimes(1);
```

Comment (mark-drastrup) [reply libs/designsystem/checkbox/src/checkbox.component.spec.ts]: Again just to make sure that the onTouched function is only called once :)

**Review by mark-drastrup — DISMISSED** [review]
Great work @AgreSanGit :D I have have some nitty gritty comments! :)

File: libs/designsystem/checkbox/src/checkbox.component.spec.ts [hunk 6]
```diff
@@ -202,4 +202,33 @@ describe('CheckboxComponent', () => {
...
+      spectator.component.registerOnChange(onChangeSpy);
+      spectator.component.onChecked(newValue);
+      expect(onChangeSpy).toHaveBeenCalledOnceWith(newValue);
+    });
+
+    it('should call the registered onTouched function when onChecked is called', () => {
+      const onTouchedSpy = jasmine.createSpy('onTouched');
+      spectator.component.registerOnTouched(onTouchedSpy);
+      spectator.component.onChecked(true);
+      expect(onTouchedSpy).toHaveBeenCalled();
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/checkbox/src/checkbox.component.spec.ts]:
```suggestion
```

I suggest to remove this line to avoid redundant expects, as it is covered by `toHaveBeenCalledTimes(1)` on the next line

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 7]
```diff
@@ -51,9 +60,49 @@ export class CheckboxComponent {
...
     this.checked = checked;
+    this._onChange(this.checked);
     this.checkedChange.emit(this.checked);
+    this._onTouched();
   }
 
   // IDs used for a11y labelling
   _labelId = UniqueIdGenerator.scopedTo('kirby-checkbox-label').next();
+
+  //ControleValueAcessor
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/checkbox/src/checkbox.component.ts]:
```suggestion
  // Initialize empty ControlValueAccessor callback functions
```
Consider giving a bit of context in this comment

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 8]
```diff
@@ -51,9 +60,49 @@ export class CheckboxComponent {
...
+    this._onTouched = fn;
+  }
+
+  /**
+   * Sets the disabled state of the checkbox.
+   * Part of the ControlValueAccessor interface.
+   */
+  setDisabledState(isDisabled: boolean): void {
+    this.disabled = isDisabled;
+  }
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Consider just copying this whole block directly from `dropdown.component.ts` (except for the implementation of writeValue of course) for consistency of comments and so on.

**Review by RasmusKjeldgaard — CHANGES_REQUESTED** [review]
Good job on implementation and test!

Apart from a couple of minor suggestions, I think the only thing missing is a good example of this in a reactive form, like we have for radio-groups: https://cookbook.kirby.design/#/home/showcase/radio

**Comment by RasmusKjeldgaard** [comment]
I think we should label this as a feature instead of a fix. I know the original issue is a bug report, but we are adding a new feature cleanly here, not fixing existing functionality.

File: apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html [hunk 9]
```diff
@@ -70,6 +70,27 @@ <h2>Checked Change Event</h2>
   >
     <cookbook-checkbox-events-example #checkboxEventsExample></cookbook-checkbox-events-example>
   </cookbook-example-viewer>
+  <h2>ngForms</h2>
+  <h3>Reactive Forms</h3>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html]:
```suggestion
  <h2>Angular Forms</h2>
```

Comment (RasmusKjeldgaard) [reply apps/cookbook/src/app/showcase/checkbox-showcase/checkbox-showcase.component.html]: I still think we can make this a bit easier to digest, possibly by adding back a little bit of the text inspired by the radio group example right below the Angular Forms heading:

> The checkbox can be used directly in [template driven](https://angular.io/guide/forms) and [reactive forms](https://angular.io/guide/reactive-forms).
> To use checkbox in a reactive form, bind your form control to <kirby-checkbox> with simple data binding:

File: apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts [hunk 10]
```diff
@@ -0,0 +1,79 @@
...
+import { FormBuilder, FormGroup, Validators } from '@angular/forms';
+
+const config = {
+  selector: 'cookbook-checkbox-reactive-forms-example',
+  template: `<form [formGroup]="form">
+  <kirby-checkbox 
+  formControlName="isChecked" 
+  text="Reactive Forms" 
+  [disabled]="!canSelectFavorite">
+  </kirby-checkbox>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts]: Consider adding a couple of checkboxes more, and reuse text from Radio Examples: 

image

File: apps/cookbook/src/app/examples/checkbox-example/checkbox-example.module.ts [hunk 11]
```diff
@@ -10,7 +11,7 @@ import { CheckboxListExampleComponent } from './examples/list';
 import { CheckboxMultilineExampleComponent } from './examples/multiline';
 import { CheckboxSizesExampleComponent } from './examples/sizes';
 import { CheckboxStatesExampleComponent } from './examples/states';
-
+import { CheckboxReativeFormsExampleComponent } from './examples/reactive-forms';
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/checkbox-example.module.ts]:
```suggestion
import { CheckboxReactiveFormsExampleComponent } from './examples/reactive-forms';

```

File: apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts [hunk 12]
```diff
@@ -0,0 +1,79 @@
...
+</form>
+<fieldset>
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts]: Consider using `cookbook-example-configuration-wrapper` here.

File: apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts [hunk 13]
```diff
@@ -0,0 +1,79 @@
...
+toggleCanSelectFavorite() {
+    this.canSelectFavorite = !this.canSelectFavorite;
+
+    if (this.canSelectFavorite) {
+      this.form.get('isChecked')?.enable();
+    } else {
+      this.form.get('isChecked')?.disable();
+    }
+  }
+    `,
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts]:
```suggestion
toggleCanSelectFavorite() {
  this.canSelectFavorite = !this.canSelectFavorite;

  if (this.canSelectFavorite) {
    this.form.get('isChecked')?.enable();
  } else {
    this.form.get('isChecked')?.disable();
  }
}
`,
```

File: apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts [hunk 14]
```diff
@@ -0,0 +1,79 @@
...
+  selector: config.selector,
+  template: config.template,
+  styleUrls: ['./ng-forms.shared.scss'],
+})
+export class CheckboxReativeFormsExampleComponent implements OnInit {
+  template: string = config.template.split('<fieldset>')[0];
+  codeSnippet: string = config.codeSnippet;
+  form: FormGroup;
+  canSelectFavorite = true;
+  favoriteRequired = true;
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts]: Consider removing `favoriteRequired` if it is not used in the example

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 15]
```diff
@@ -3,12 +3,14 @@ import {
...
   Component,
   EventEmitter,
+  forwardRef,
   HostBinding,
   Input,
   Output,
 } from '@angular/core';
 import { IonicModule } from '@ionic/angular';
 import { UniqueIdGenerator } from '@kirbydesign/designsystem/helpers';
+import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Please consider readability: order and grouping of imports: 
```suggestion
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

import { UniqueIdGenerator } from '@kirbydesign/designsystem/helpers';
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 16]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
...
     this.checked = checked;
+    this._onChange(this.checked);
     this.checkedChange.emit(this.checked);
+    this._onTouched();
   }
 
   // IDs used for a11y labelling
   _labelId = UniqueIdGenerator.scopedTo('kirby-checkbox-label').next();
+
+  // Initialize empty ControlValueAccessor callback functions
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Consider wording:
```suggestion
  // Initialize default ControlValueAccessor callback functions (noop)
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 17]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
...
+  // eslint-disable-next-line no-empty-function
+  private _onChange: (value: boolean) => void = () => {};
+  // eslint-disable-next-line no-empty-function
+  private _onTouched = () => {};
+
+  /**
+   * Sets the select's value. Part of the ControlValueAccessor interface
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Copy pasted from somehere? ;)
```suggestion
   * Sets the checkbox's value. Part of the ControlValueAccessor interface
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 18]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
...
+   * required to integrate with Angular's core forms API.
+   *
+   * @param value New value to be written to the model.
+   */
+  writeValue(value: boolean): void {
+    this.checked = value;
+  }
+
+  /**
+   * Saves a callback function to be invoked when the select's value
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Copy pasted from somehere? ;)
```suggestion
   * Saves a callback function to be invoked when the checkbox's value
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 19]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
...
+   * required to integrate with Angular's core forms API.
+   *
+   * @param fn Callback to be triggered when the value changes.
+   */
+  registerOnChange(fn: any): void {
+    this._onChange = fn;
+  }
+
+  /**
+   * Saves a callback function to be invoked when the select is blurred
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Copy pasted from somehere? ;)
```suggestion
   * Saves a callback function to be invoked when the checkbox is blurred
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 20]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
...
+   * to integrate with Angular's core forms API.
+   *
+   * @param fn Callback to be triggered when the component has been touched.
+   */
+  registerOnTouched(fn: any): void {
+    this._onTouched = fn;
+  }
+
+  /**
+   * Disables the select. Part of the ControlValueAccessor interface required
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: Copy pasted from somehere? ;)
```suggestion
   * Disables the checkbox. Part of the ControlValueAccessor interface required
```

File: libs/designsystem/checkbox/src/checkbox.component.ts [hunk 21]
```diff
@@ -51,9 +60,59 @@ export class CheckboxComponent {
 
   onChecked(checked: boolean): void {
     this.checked = checked;
+    this._onChange(this.checked);
     this.checkedChange.emit(this.checked);
+    this._onTouched();
```
Comment (jakobe) [inline libs/designsystem/checkbox/src/checkbox.component.ts]: This should be called on blur, not when checked state changes.

**Review by jakobe — CHANGES_REQUESTED** [review]
Hi @AgreSanGit ,

1 important comment and a few copy-pastes to fix ;)

**Review by RasmusKjeldgaard — APPROVED** [review]

File: apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts [hunk 22]
```diff
@@ -0,0 +1,135 @@
...
+  </cookbook-example-configuration-wrapper>`,
+  codeSnippet: `checkboxes: { id: string; label: string }[] = [
+    { id: 'Bacon', label: 'Bacon' },
+    { id: 'Salami', label: 'Salami' },
+    { id: 'Tenderloin', label: 'Tenderloin' },
+  ];
+  
+  form: FormGroup;
+  canSelectFavorite = true;
+  formValue: any;
```
Comment (RasmusKjeldgaard) [inline apps/cookbook/src/app/examples/checkbox-example/examples/reactive-forms.ts]: I think we should clean this example up, so it is easier to understand.
Let us talk about this thursday!

**Review by RasmusKjeldgaard — CHANGES_REQUESTED** [review]

**Review by RasmusKjeldgaard — APPROVED** [review]

**Review by jakobe — APPROVED** [review]
