### PR TITLE
Badge: Fix missing theme color when used as standalone component

### LINKED ISSUE #3319: [BUG] Badge is missing theme colors when used as standalone component
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
When importing Badge as a standalone component the `ThemeColorDirective` is not applied because of [the way Angular works with imported directives](https://angular.io/guide/standalone-components#the-standalone-flag-and-component-imports) in standalone components.

**TL;DR** Imported directives in standalone components are only applied to the component's template, not the component itself. For this to work [the directive needs to be specified in the component decorator's `hostDirectives` property](https://angular.io/guide/directive-composition-api#adding-directives-to-a-component).

## Describe how to reproduce the bug
1. Create a blank Angular application
2. Import the `BadgeComponent` (_not_ the entire `KirbyModule`)
3. Use the Badge with themeColor applied: `<kirby-badge themeColor="danger">I'm not red :(</kirby-badge>`
4. See the Badge **not** being rendered with danger color

## Which Kirby version was used?
9.0.0 

## What was the expected behavior?
Themecolor being applied correctly when importing the Badge as a standalone component.

## Are there any additional context?
The test for Badge imports the `ThemeColorDirective` which gives a false positive on the theme color tests. This should be removed.
This also applies to the Avatar component.

Additionally the ModalFooter component uses the `ThemeColorDirective` only to apply the `light` css class. This could/should be changed to a `HostBinding` attribute instead for simplicity.

<hr />

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](../CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

### PR DESCRIPTION
**Pull request by jakobe**
## Which issue does this PR close?

This PR closes #3319 

## What is the new behavior?

Theme color is applied correctly when imported as standalone component.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Reminders
- [x] Make sure you have implemented tests following the guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)".
- [x] Make sure you have updated the cookbook with examples and showcases (for bug fixes, enhancements & new components).

### Review  
- [x] Determine if your changes are a fix, feature or breaking-change, and add the matching label to your PR. If it is tooling, dependency updates or similar, add ignore-for-release.
- [x] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review).
- [x] Request that the changes are code-reviewed 
- [x] Request that the changes are [UX reviewed](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#ux-review) (only necessary if your PR introduces visual changes)

When the pull request has been approved it will be merged to `develop` by Team Kirby.

### CODE REVIEW

File: libs/designsystem/badge/src/badge.component.ts [hunk 1]
```diff
@@ -10,11 +10,14 @@ export type BadgeSize = 'sm' | 'md';
...
   styleUrls: ['./badge.component.scss'],
   standalone: true,
-  imports: [CommonModule, KirbyIonicModule, ThemeColorDirective],
+  imports: [CommonModule, KirbyIonicModule],
+  hostDirectives: [{ directive: ThemeColorDirective, inputs: ['themeColor'] }],
 })
 export class BadgeComponent {
   @Input() text: string;
 
+  @Input() themeColor: 'success' | 'warning' | 'danger' = 'success';
```
Comment (RasmusKjeldgaard) [inline libs/designsystem/badge/src/badge.component.ts]: There is an unfortunate difference between what we say the allowed values for ThemeColor is in the badge docs, and what was actually enforced in code. Before this I guess we allowed any themeColor, so this could be breaking 😕 

Furthermore `SegmentItemBadge` used for badges in the `SegmentedControl` allows using all of the ThemeColor type, so we get a compile error when building the lib:
image

I think it would be best to allow using any ThemeColor for badge to avoid breaking changes in projects. Then possibly schedule a breaking change for the next major if we want to narrow it like here.

**Review by RasmusKjeldgaard — CHANGES_REQUESTED** [review]
Nice boyscouting! Aside from the proposed fix, consider renaming the PR title to 
> Badge: Fix missing theme color when used as standalone component

to conform with our (very _very_ informal) standard 😄

**Review by RasmusKjeldgaard — APPROVED** [review]
Awesometastic, only comment is that I still think you should consider renaming the PR title to

    Badge: Fix missing theme color when used as standalone component

to conform with our (very very informal) standard 😄
