### PR TITLE
Fix/modal header enhancements

### LINKED ISSUE #280: [Enhancement] Modal - placement of close button
**Is your enhancement request related to a problem? Please describe.**
Modal should have the option to specify the placement of the close button. 

There are two cases, because the close button can either be inside the modal or outside the modal.

See also: https://zpl.io/VqvzKGl

### LINKED ISSUE #281: [BUG] Kirby Modal's Heading text is overlapping.
**Describe the bug**
Modal heading text is overlapping with modal cross button/icon.

**To Reproduce**
- Just open the Kirby modal in native app

**Kirby version**
 -  0.0.136

**Expected behavior**
MODAL heading text should not overlap with the modal close button and it should be on left side of the close button with considerable margin.

**Screenshots**
image.

**Native (please complete the following information):**
 - Device: iPhone & Android device

**Additional context**
              - -

### LINKED ISSUE #293: [Enhancement] Close button as property to show/not show
**Is your enhancement request related to a problem? Please describe.**
We want to be able to have a property for the close button to show/not show, because we are  probably going to have some modals without any close buttons, that only respond to a close button in the modal.

### PR DESCRIPTION
**Pull request by mmmtrifork**
Note that this is not the finalised modal styling, but various header improvements were added, including a fix for the button position on the screen. 

fixes #280, fixes #281, fixes #293

### CODE REVIEW

File: src/kirby/components/modal/modal-wrapper/config/modal-config.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 export interface ModalConfig {
   title: string;
-  titleHorizontalAlignment?: 'left' | 'center';
```
Comment (unnamjolner) [inline src/kirby/components/modal/modal-wrapper/config/modal-config.ts]: We are using this property to set alignment of title (as on attached wireframes). Would it still be possible with the changes in this PR?
Screenshot 2019-05-21 at 12 56 35

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.html [hunk 2]
```diff
@@ -1,15 +1,17 @@
 <div class="modal-wrapper" #modalWrapper tabindex="-1" (window:focus)="onFocusChange()" (window:focusout)="onFocusChange()">
     <div class="modal-header">
-        <h2 class="text-{{config.titleHorizontalAlignment}} title">{{ config.title }}</h2>
-    </div>
+        <div class="title-container">
+            <span class="text-{{config.closeBtnPlacement === 'inside' ? 'left' : 'center'}} title">{{ config.title }}</span>
```
Comment (unnamjolner) [inline src/kirby/components/modal/modal-wrapper/modal-wrapper.component.html]: I would move this to a method in the controller to avoid repeating the logic for web and {N}

File: src/kirby/components/modal/modal-wrapper/config/modal-config.ts (hunk 1 above)
Comment (unnamjolner) [reply src/kirby/components/modal/modal-wrapper/config/modal-config.ts]: Maybe we should just have @bommariusser to comment on this. I take it he gave the instructions :)

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.spec.ts [hunk 3]
```diff
@@ -9,7 +9,7 @@ import { IconComponent } from '../../icon/icon.component';
 import { ModalWrapperComponent } from './modal-wrapper.component';
 import { IModalController } from '../services/modal.controller.interface';
 
-describe('ModalWrapperComponent', () => {
+fdescribe('ModalWrapperComponent', () => {
```
Comment (unnamjolner) [inline src/kirby/components/modal/modal-wrapper/modal-wrapper.component.spec.ts]: Oopsie ;)

Comment (mmmtrifork) [reply src/kirby/components/modal/modal-wrapper/modal-wrapper.component.spec.ts]: was just thinking that i might have forgotten to remove the fdescribe :D ...

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.html (hunk 2 above)
Comment (mmmtrifork) [reply src/kirby/components/modal/modal-wrapper/modal-wrapper.component.html]: this logic has changed now, so i'll resolve this comment for now

File: src/app/examples/modal-example/modal-example.component.ts [hunk 4]
```diff
@@ -14,7 +14,7 @@ export class ModalExampleComponent {
   showModal() {
     const config: ModalConfig = {
       title: 'First Embedded Modal',
-      titleHorizontalAlignment: 'center',
+      closeBtnPlacement: 'inside',
```
Comment (jakobe) [inline src/app/examples/modal-example/modal-example.component.ts]: Consider renaming to:
```suggestion
      closeBtnPosition: 'inside',
```

File: src/app/showcase/modal-showcase/modal-showcase.component.ts [hunk 5]
```diff
@@ -19,17 +19,23 @@ export class ModalShowcaseComponent {
       inputValues: ['string'],
     },
     {
-      name: 'titleHorizontalAlignment',
-      description: 'The horizontal alignment of the title',
-      defaultValue: 'center',
-      inputValues: ['left', 'center'],
+      name: 'closeBtnPlacement',
```
Comment (jakobe) [inline src/app/showcase/modal-showcase/modal-showcase.component.ts]: Consider renaming to:
```suggestion
      name: 'closeBtnPosition',
```

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.scss [hunk 6]
```diff
@@ -6,33 +6,50 @@
...
-
-    .text-left {
-      text-align: left;
+    display: flex;
+    justify-content: flex-end;
+    padding: size('s');
+    
+    .title-container {
+      width: 100%;
+      display: inline-table;
```
Comment (jakobe) [inline src/kirby/components/modal/modal-wrapper/modal-wrapper.component.scss]: ??

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.scss [hunk 7]
```diff
@@ -6,33 +6,50 @@
...
+
+      .title {
+        height: 40px;
+        vertical-align: middle;
+        display: table-cell;
```
Comment (jakobe) [inline src/kirby/components/modal/modal-wrapper/modal-wrapper.component.scss]: ??

File: src/kirby/components/modal/modal-wrapper/modal-wrapper.component.tns.html [hunk 8]
```diff
@@ -1,16 +1,22 @@
...
-                <kirby-floating-action-button [showShadow]="false" (tap)="onModalDismiss()">
-                    <kirby-icon [name]="config.closeIconName"></kirby-icon>
-                </kirby-floating-action-button>
-            </AbsoluteLayout>
+        <GridLayout rows="auto, *" columns="*, auto" class="title-bar">
+
+            <Label class="title" row="0" col="0" verticalAlignment="center" horizontalAlignment="{{ config.titleHorizontalAlignment }}" textWrap="true"
+                    text="{{ config.title }}"></Label>
+            
+            <kirby-floating-action-button *ngIf="config.closeBtnPlacement === 'inside'" [showShadow]="false" (tap)="onModalDismiss()" row="0" col="1">
```
Comment (jakobe) [inline src/kirby/components/modal/modal-wrapper/modal-wrapper.component.tns.html]: Seems a bit duplicated... Can't you achieve this with same GridLayout? Placing on same row stacks the elements...

Comment (mmmtrifork) [reply src/kirby/components/modal/modal-wrapper/modal-wrapper.component.tns.html]: I am not sure I understand, they are currently placed in a GridLayout, on the same row, but different columns

Comment (mmmtrifork) [reply src/kirby/components/modal/modal-wrapper/modal-wrapper.component.tns.html]: fixed now 👍
