### PR TITLE
Make it possible to remove list item color class

### LINKED ISSUE #1336: [BUG] Can't change list color after it is set
**Describe the bug**

Can't change list color after it is set as the css color directive in list component is only appending color classes but is not able to change them later.

**To Reproduce**

1. Add color to list item using color CB
2. Try to change color
3. See still same color as in step 1

**Kirby version**
- [e.g. 1.1.10]

**Expected behavior**

**Please complete the following information:**
- OS: [e.g. Windows, MacOS, iOS]
- Browser [e.g. Chrome, Safari]
- Browser version [e.g. 22]

**Additional context**

## Tasks:
- [x] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [x] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

### PR DESCRIPTION
**Pull request by lydemann**
This PR closes #1336

Make it possible to remove list item color class

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] cookbook application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/designsystem/src/lib/components/list/directives/list-item-color.directive.ts [hunk 1]
```diff
@@ -8,17 +8,20 @@ import { ThemeColor } from '../../../helpers/theme-color.type';
...
 
-  ngOnChanges(changes: SimpleChanges): void {
+  private getColor(): ThemeColor {
     if (!this.kirbyListItemColor || !this.item) {
       return;
     }
 
     const themeColor = this.kirbyListItemColor(this.item);
-    this.renderer.addClass(this.elementRef.nativeElement, themeColor);
+    return themeColor;
```
Comment (jakobe) [inline libs/designsystem/src/lib/components/list/directives/list-item-color.directive.ts:25]: Consider simplifying:
```suggestion
    return this.kirbyListItemColor(this.item);
```

**Review by jakobe — APPROVED** [review]
